### ISSUE TITLE
JSON\YML being served by the wrong server

### ISSUE THREAD

**Issue by dransk** [vazco/meteor-universe-i18n#10]
The application I'm currently working on is a widget so there's always the need for the two servers. One, running on port 1337 and the server for the widget which is running on port 3000.
Despite the fact that the translation files exist on the widget server, everytime Universe tries to load the file, it tries on the following URL: localhost:1337. Considering that the URL returns an HTML page, the application ends up crashing producing the error: "Uncaught SyntaxError: Unexpected token <".
The whole problem here is that universe should be making the request based on the port where it's running and not on the one that loads the widget.

**Comment by cristo-rabani** [comment]
Hello,
Please make an update to version 1.3.3.
As a default i18n gets host from Meteor.absoluteUrl(), but you can change this url by overriding property `_i18n.options.hostUrl` before calling method `_i18n.setLocale(fr-fr)`
