### ISSUE TITLE
loading json configs without eager loading from meteor

### ISSUE THREAD

**Issue by rockettomatooo** [vazco/meteor-universe-i18n#103]
I came across this package because its the most active maintained i18n package according to my research. Thanks for keeping up the good work!

My app currently runs on `meteor@1.7.0.3` and I already switched to meteors new module system which just specifies 2 entrypoints for client and server like so:

```json
// package.json

{
  ...
  "meteor": {
    "mainModule": {
      "client": "startup/client.js",
      "server": "startup/server.js"
    }
  }
}
```

As a result of this, no files are actually eagerly loaded but only when they are actively imported *(if that makes sense lol)*. Have a look at the [v1.7 changelog from meteor](https://docs.meteor.com/changelog.html#v1720180528) for details.

I store my translations in `app-root/ressources/locales/*.i18n.json` and have set the `_locale` and `_namespace` in all my json files. However I don't get i18n to recognize them.

I already tried the following things:
  - just importing them like `import '/ressources/locales/en.i18n.json'` *(on client- (and server-)side)*
  - `require()` them and put its content into `i18n.addTranslations()` *(however, the result of `require()` always was a blank object)*
  - take a quick look at your source code and try to figure out how you detect the translations.

... and apparently, I'm running out of ideas :D

Does anyone have a suggestion how to get my translations into i18n?

Hint: I use the current stable version of `universe:i18n` which is `1.16.1`.

Here's a sample of one of my json files:

```json
{
  "_namespace": "common",
  "_locale": "de-DE",
  "errors": {
    "notFound": "{$label} konnte nicht gefunden werden.",
    "nonExistent": "{$label} existiert nicht."
  }
}
```

**Comment by dovydaskukalis** [comment]
Did you find a solution?

**Comment by majeocpi** [comment]
https://github.com/vazco/meteor-universe-i18n/issues/88#issuecomment-388341901

**Comment by ivan133** [comment]
For me the solution of comment #88 didn't work

**Comment by ivan133** [comment]
Ok

I'm using meteor 1.7
My package.json contains:

```
  "meteor": {
    "mainModule": {
      "client": "startup/client/index.js",
      "server": "startup/server/index.js"
    }
  },
```

on startup/client/index.js I've added :

```
import './i18n';
```
And here is ./i18n itself: 

```
import i18n from 'meteor/universe:i18n';
import { Meteor } from 'meteor/meteor';
import { Tracker } from 'meteor/tracker';
import '/i18n/en.i18n.json';
import '/i18n/he.i18n.json';

const deviceLocale = getLang();

i18n.setOptions({
  defaultLocale: deviceLocale,
  sameLocaleOnServerConnection: true
});

Meteor.startup(() => {
  Tracker.autorun(() => {
    const user = Meteor.user();

    if (user) {
      const locale = user.profile.lang || deviceLocale;

      i18n.setLocale(locale);
    } else {
      i18n.setLocale(deviceLocale);
    }
  });
});

function getLang() {
  const defaultLang = 'he-IL';
  const locales = ['en', defaultLang, 'he-IL', 'he'];

  let result =
    (navigator.languages && navigator.languages[0]) ||
    navigator.language ||
    navigator.browserLanguage ||
    navigator.userLanguage ||
    defaultLang;

  if (!locales.includes(result)) {
    result = defaultLang;
  }

  return result;
}
```


and it worked!!!

**Comment by ivan133** [comment]
Actually, my way doesn't load all the files on the server (I've added)  UNIVERSE_I18N_LOCALES to env variables
