### ISSUE TITLE
How to get plain translation in defaultProps?

### ISSUE THREAD

**Issue by Sir-Will** [vazco/meteor-universe-i18n#120]
How do you use the translations in React's `defaultProps`  to get the plain string?

Using `<T>common.loading.loading</T>` works but throws warnings because the propType is set to string and it doesn't return a plain string.
```
Warning: Failed prop type: Invalid prop `title` of type `object` supplied to `Loading`, expected `string`.
```

`i18n.getTranslation('common', 'loading', 'pleaseWait')` is supposed to return it as plain string but it returns the key and not the translation under default Props.

```javascript
Loading.defaultProps = {
  title: <T>common.loading.loading</T>,
  subtitle: i18n.getTranslation('common', 'loading', 'pleaseWait'),
};
```

**Comment by Sir-Will** [comment]
Found the issue, the translation files were being loaded to late.

**Comment by radekmie** [comment]
Hi @Sir-Will. It's good that you've managed to find the issue by yourself, but let me answer it anyway. Component `T` will create a React element, therefore it'll be an object. Using `getTranslation` as a default prop may not be a good idea as it'll be calculated once and won't refresh on language change. It'd be better to use default argument to do so.

**Comment by Sir-Will** [comment]
Hey @radekmie, thank you.
What do you mean by using a default argument?

**Comment by radekmie** [comment]
It's also called _default parameter_ ([MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters)). It'd look like this:
```tsx
function MyComponent({ subtitle = i18n.getTranslation('key') }) {
  // ...
}
```

**Comment by Sir-Will** [comment]
Ah okay, thanks.
