### ISSUE TITLE
Meteor getTranslation issue

### ISSUE THREAD

**Issue by Gosselk** [vazco/meteor-universe-i18n#121]
hi, 

With the following code I get no results: 
[Main.js pastebin](https://pastebin.com/F2ALr8CT)

This console.log return "accueil" and not the content of the Json 

my json : 
`{
  "_locale": "fr-FR",
  "_namespace": "common",
  "accueil": "it's juste a test "
}`

I don't know if it's a mistake or a misunderstanding.

Thanks , and sorry for my bad english.

**Comment by radekmie** [comment]
Hi @Gosselk. Can you try `i18n.__('common.accueil')` instead? I think the issue is that your translations are namespaced (`"_namespace": "common"`).

If it won't work, please share here the output of `i18n.getTranslations()`.

**Comment by Gosselk** [comment]
yes it's work like that ... It's a mistake from me.. sorry and thanks for your help
