### ISSUE TITLE
Multiline translation?

### ISSUE THREAD

**Issue by Sir-Will** [vazco/meteor-universe-i18n#122]
Is there a way to be able to have multiline translations without having to create a new key for each line?
I tried adding `\n` to the translation but it is removed without adding a new line.

Adding `white-space: pre-wrap;` to the `span` seems to work but is that the best approach for this?

**Comment by radekmie** [comment]
Hi @Sir-Will. In JSON, you'd have to manually add `\n` in the translation file. In YAML, you can either use `\n`, or use the [multiline string syntax](https://yaml-multiline.info/):
```yml
greet: |-
  Nice to see you,
  sunshine!
```

In both cases, it'll produce a string with `\n` in it, and it's up to you, how to render that. This `white-space` CSS solution may work, but you could split the string on `\n` and display each line _somehow_ separately instead.

**Comment by Sir-Will** [comment]
Thanks for the reply.
So universe-i18n doesn't provide an option to return the React component with `<br />`?
I thought there might be a parameter/argument which would make it to split the translation string by `\n` and then return multiple `<span>` elements with `<br />`.

**Comment by radekmie** [comment]
No, it does not. To be honest, we are not using this `T` component ourselves (and it's quite dated). I suggest you to create your own component, [based on it](https://github.com/vazco/meteor-universe-i18n/blob/77899915ddbbaec96d8d7358b92c7d1a39acfb6e/lib/i18n.js#L86-L131). If you do, you are more than welcome to share it here.
