### ISSUE TITLE
I cannot translate placeholder using i18n and React

### ISSUE THREAD

**Issue by italianog** [vazco/meteor-universe-i18n#123]
Hi,
I'm using React and i18n to translate my App in different languages.
I'm facing this issue: I cannot translate placeholders. This is my code:

`
class FormExample extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      nome: "",
      email: "",
      testo: "",
      success: false,
    };
    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

```
  render() {
    const { t } = this.props;
    return (
      <div>
        <form className="test-mailing">
          <div>
            <FormInput
              name="nome"
              type="text"
              value={this.state.nome}
              required
              handleChange={this.handleChange}
              placeholder={t("placeholder.nome")}
            />

```
`export default withTranslation()(FormExample);`
`
This is the entry inside my json:

	"placeholder": {
		"nome": "Name"
	},
Can you help me please? Thanks

**Comment by radekmie** [comment]
Hi @italianog. What is `withTranslation` exactly? It's not a part of `universe:i18n`. Also, could you elaborate a little on _I cannot translate placeholders_? Tell us what happens, if there's an error, etc.

**Comment by radekmie** [comment]
I hope everything works now. If not, feel free to comment here or file a new issue.
