### ISSUE TITLE
Avoid warning

### ISSUE THREAD

**Issue by sabativi** [vazco/meteor-universe-i18n#126]
Hello,
There is a json parser which I think cause a problem here : https://github.com/vazco/meteor-universe-i18n/blob/master/server/api.js#L110 

```
W20210308-14:31:41.040(1)? (STDERR) FetchError: invalid json response body at http://localhost:3000/universe/locale/pl reason: Unexpected token ( in JSON at position 0
W20210308-14:31:41.040(1)? (STDERR)     at /Users/sabativi/.meteor/packages/fetch/.0.1.1.u1snce.3x0j++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/node-fetch/lib/index.js:241:32
W20210308-14:31:41.040(1)? (STDERR)     at /Users/sabativi/.meteor/packages/promise/.0.11.2.gnlx4b.qufrv++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20210308-14:31:41.040(1)? (STDERR)  => awaited here:
W20210308-14:31:41.040(1)? (STDERR)     at Function.Promise.await (/Users/sabativi/.meteor/packages/promise/.0.11.2.gnlx4b.qufrv++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20210308-14:31:41.041(1)? (STDERR)     at packages/universe:i18n/server/api.js:110:19
W20210308-14:31:41.041(1)? (STDERR)     at /Users/sabativi/.meteor/packages/promise/.0.11.2.gnlx4b.qufrv++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40 {
W20210308-14:31:41.041(1)? (STDERR)   type: 'invalid-json'
W20210308-14:31:41.041(1)? (STDERR) }
```

When I look at this url `http://localhost:3000/universe/locale/pl` there is no JSON content but I guess plain text

I have no problem on production but with 5 translations files I have 5 warnings every reload.

If you have any clue ?

Ps : I am using [simple-rest](https://github.com/stubailo/meteor-rest)

**Comment by radekmie** [comment]
Hi @sabativi. We'll try to look into it soon.

**Comment by sabativi** [comment]
@radekmie can I help ?

**Comment by radekmie** [comment]
Definitely, @sabativi! If you could prepare a reproduction, it'd be much much easier for us to pick it up. I know that it takes time, so we could debug it step by step. At first, you could fork the package (clone the repo and put it in the `packages` directory), and check, what kind of response is received there (e.g., `console.log(await data.text())`). I haven't used `simple:rest` with this package and it _may_ be a good lead.

**Comment by radekmie** [comment]
As there's no reproduction and we're not using the `simple:rest` package, we're closing this one. If you'll encounter this problem -- let us know.
