### ISSUE TITLE
Won't accept certain locale settings, like en-DE (Samsung Browser)

### ISSUE THREAD

**Issue by derwaldgeist** [vazco/meteor-universe-i18n#128]
In some circumstances, Samsung's default web browser on Android might report weird language combinations like `en-DE`. I am not quite sure why exactly this happens, but I noticed that in this case `universe:i18n` throws an error:

```Wrong locale: en-DE [Should be xx-yy or xx]```

instead of just falling back to `en`.

Tested on a Samsung Galaxy S10 5G

It might be related to the fact that I switched my device to English, but it originally was installed with a German locale.

**Comment by radekmie** [comment]
Hi @derwaldgeist. Can you consistently reproduce it? If so, please include your Android and browser versions as well. Also, _when_ it threw an error (startup, `setLocale`, etc.)?

**Comment by derwaldgeist** [comment]
Hi @radekmie: Yes, this is consistently reproducible. It happens when calling `setLocale()`. As a workaround, I am limiting the locale to 2 characters only for now, which works for my app at the moment, but may not in the future once we support more locales.

Android version is 11, under One UI version 3.1. The version of the Samsung browser is Samsung Internet 14.0.1.62. The web view being used is Android System WebView 90.0.4430.91 (according to the Android developer settings).

**Comment by radekmie** [comment]
OK, understood. I was more concerned about the `en-DE` locale as it's something I've never heard of.

> As a workaround, I am limiting the locale to 2 characters [...]

As I've checked, we do that in our projects as well. Do you have a case, where something is actually locale-sensitive?

**Comment by derwaldgeist** [comment]
Sure. If your client is located in Switzerland, for instance. Swiss German is very similar, but lacks the letter "ß". They write it as "ss". So there is actually a difference between "de-DE" and "de-CH". Another, more important variant is "Rio de la Plata Spanish", which has quite some differences from Spanish spoken in Spain.

**Comment by radekmie** [comment]
Thanks for the insights! In this case, updating the [`normalize`](https://github.com/vazco/meteor-universe-i18n/blob/d1c42ddc5cca8799dc61d87593b0f40ca55558c2/lib/i18n.js#L11-L15) helper should be enough. I'll try to look into it this week.

**Comment by derwaldgeist** [comment]
Awesome!

**Comment by radekmie** [comment]
Before we roll out an update, please do check whether this implementation works for you. It does a little bit more, i.e., takes care of some [less common locale formats](https://github.com/vazco/meteor-universe-i18n/blob/d1c42ddc5cca8799dc61d87593b0f40ca55558c2/lib/locales.js#L46-L50).
```ts
i18n.normalize = function normalize(locale) {
  const parts = locale.toLowerCase().split(/[\-_]/);
  while (parts.length) {
    const locale = parts.join('-');
    if (locale in i18n._locales) {
      return i18n._locales[locale][0];
    }

    parts.pop();
  }

  return null;
};
```

**Comment by piotrpospiech** [comment]
Issue was fixed in the https://github.com/vazco/meteor-universe-i18n/pull/130
