### ISSUE TITLE
possibility of usage react installed from npm

### ISSUE THREAD

**Issue by newsiberian** [vazco/meteor-universe-i18n#13]
Hello, I'm not sure my question is correct, but is it possible to make package to work with `react` installed from npm? I'm testing with `METEOR@1.3-modules-beta.5`
Currently I got an error:
`React is not detected! i18n.js:53`

**Comment by teknologist** [comment]
+1

**Comment by cristo-rabani** [comment]
Hello, 
Actually, You can pass React instance as a last parameter
of function `createComponent`. 

In next version we should add auto detection for new modules system.

**Comment by nmaro** [comment]
+1
is there a way to pass the react instance to __()?

**Comment by nmaro** [comment]
Nevermind my last question, react is of course not needed for that function ;)
