### ISSUE TITLE
Sharing good practices

### ISSUE THREAD

**Issue by sabativi** [vazco/meteor-universe-i18n#131]
Hello,

I am more than happy that this project is vamping up !

I have taken a look at the PR and I am already replacing react component by simple strings.
What I want with this issue is to share best practice.

Especially, when I code, I do not want to be disturb with translations, I just write string in the main languages of my app.

After that I have two things to do :

1. Find hardcoded strings and put them inside my main_langage.json file
2. Add those new keys inside all my other langages json files and translate them

Do you have best practice on how do you do that ? Any advice ?

I find this to be not really interesting, and time consuming so any advice would really help.

Thanks

**Comment by radekmie** [comment]
I'll add my two cents here, about the "package for easy tracking and translating". We have an in-house tool (package) for that. It basically renders a table where the rows are the strings (e.g., `common.yes`, `forms.labels.firstName`), the columns are the languages (e.g., `en`, `de`), and the cells are the actual translations. It's fairly simple, but we have made a pretty decent UI for it, including user-friendly UX for large updates (e.g., a translator adding an entirely new language). Our plan is to investigate, how to distribute something like this as a package.
