### ISSUE TITLE
Error after updating to 1.32.0

### ISSUE THREAD

**Issue by ixdi** [vazco/meteor-universe-i18n#132]
Hi,
Working with 1.31.0 was fine but when updating to the new 1.32.0 many errors occur of the type
```
languages/en/accounts.en.i18n.json: Cannot find locale for file "[object Object]"
```
This occurs for each of the translate files that we have.

I added @types/meteor-universe-i18n and we are developing with Blaze

Any ideas? Thanks

**Comment by crtkl-mdoll** [comment]
I'm getting this too with files structured like `/i18n/en/app.en.i18n.yml`

**Comment by jmdsg** [comment]
Same issue here.

**Comment by TimHeckel** [comment]
Ditto on the issue.

**Comment by radekmie** [comment]
Hi all and thanks for the report! We'll look into it soon.

**Comment by piotrpospiech** [comment]
Hi everyone, new package version `1.32.1` was released. Can you check if this problem persists? Let me know if it will be still problem with this package.

**Comment by crtkl-mdoll** [comment]
> Hi everyone, new package version `1.32.1` was released. Can you check if this problem persists? Let me know if it will be still problem with this package.

I'm still getting the same errors.  Give this branch of my boilerplate app a try and see if you can reproduce it. https://github.com/ArchiCroc/pup-plus/tree/i18n-issue
Maybe I'm doing something wrong that needs better documentation.

**Comment by TimHeckel** [comment]
The issue is in the `analyzePath` function inside `compiler.ts` - I don't have the time atm to do a proper PR, but tweaking that function to use this fixed the issue for me:

```
function analyzePath(sourcePath: string) {
  const parsed = path.parse(sourcePath);
  const type = parsed.ext;
  const localeAsDirectory = parsed.dir.includes('i18n/');
  const locale = localeAsDirectory ? parsed.dir.substring(parsed.dir.lastIndexOf('/') + 1) : path.basename(sourcePath, `.i18n${type}`)
  return { locale, type };
}
```

**Comment by TimHeckel** [comment]
^ actually nevermind about not having the time to create a proper PR; just made one using the above code for this issue

**Comment by suneethdev** [comment]
Hi @piotrpospiech @radekmie i still have this issue, i have recently updated the version to 1.32.1. and now my app is not running. 
My code for importing the translation file:
`import '/imports/languages/en/en.login.i18n.yml';`
Error:
`imports/languages/en/en.login.i18n.yml: Cannot find locale for file "[object Object]".`

Thanks in advance.
