### ISSUE TITLE
Error after updating 1.32.0

### ISSUE THREAD

**Issue by zeearth** [vazco/meteor-universe-i18n#133]
Hi everybody

I just update meteor to th 2.3.5 and universe*i18n updating to 1.32.0
When I start my project I have an error : cannot find module 'strip-json-comments'

` Error: Cannot find module 'strip-json-comments'
W20210820-11:42:45.452(2)? (STDERR)     at makeMissingError (packages\modules-runtime.js:222:12)
W20210820-11:42:45.452(2)? (STDERR)     at Module.require (packages\modules-runtime.js:241:17)
W20210820-11:42:45.452(2)? (STDERR)     at Module.moduleLink [as link] (C:\Users\myUser\AppData\Local\.meteor\packages\modules\0.16.0\npm\node_modules\reify\lib\runtime\index.js:52:22)
W20210820-11:42:45.452(2)? (STDERR)     at module (packages/universe:i18n/source/server.ts:2:29)
W20210820-11:42:45.453(2)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20210820-11:42:45.453(2)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20210820-11:42:45.453(2)? (STDERR)     at require (packages\modules-runtime.js:258:21)
W20210820-11:42:45.453(2)? (STDERR)     at C:\dev\src\mpec\NextGen\fytorio\.meteor\local\build\programs\server\packages\universe_i18n.js:1905:15
W20210820-11:42:45.454(2)? (STDERR)     at C:\dev\src\mpec\NextGen\fytorio\.meteor\local\build\programs\server\packages\universe_i18n.js:1913:3
W20210820-11:42:45.454(2)? (STDERR)     at C:\dev\src\mpec\NextGen\fytorio\.meteor\local\build\programs\server\boot.js:401:38
W20210820-11:42:45.454(2)? (STDERR)     at Array.forEach (<anonymous>)
W20210820-11:42:45.454(2)? (STDERR)     at C:\dev\src\mpec\NextGen\fytorio\.meteor\local\build\programs\server\boot.js:226:21
W20210820-11:42:45.454(2)? (STDERR)     at C:\dev\src\mpec\NextGen\fytorio\.meteor\local\build\programs\server\boot.js:464:7
W20210820-11:42:45.455(2)? (STDERR)     at Function.run (C:\dev\src\mpec\NextGen\fytorio\.meteor\local\build\programs\server\profile.js:280:14)
W20210820-11:42:45.455(2)? (STDERR)     at C:\dev\src\mpec\NextGen\fytorio\.meteor\local\build\programs\server\boot.js:463:13`

Do you need someting else ?
I have tried 

- npm install strip-json-comments
- meteor npm install strip-json-commets
- npm install -g strip-json-comments

Best regards

**Comment by radekmie** [comment]
Hi @zeearth. Thanks for the report! We'll look into it soon.

**Comment by piotrpospiech** [comment]
Issue is fixed in a new package version `1.32.1`
