### ISSUE TITLE
Problems with Meteor-1.3-beta.8

### ISSUE THREAD

**Issue by newsiberian** [vazco/meteor-universe-i18n#14]
Hello, I trying to run package with new Meteor version and I faced with few problems.
First I can't access to `i18n` via `import { i18n } from "meteor/universe:i18n";` but this: `import { _i18n } from "meteor/universe:i18n";` works.
Then the translations from files aren't picked up by package. I have two files: `en.i18n.json` and `ru.i18n.json`. They were working fine before.

**Comment by cristo-rabani** [comment]
Hello, 
This bug is in meteor core and issue is already reported (https://github.com/meteor/meteor/issues/6031) 

For now only yml translations files work in meteor 1.3 beta
