### ISSUE TITLE
Roadmap to v2

### ISSUE THREAD

**Issue by radekmie** [vazco/meteor-universe-i18n#144]
This issue will be updated later.

---

Our main goal is to make the package lighter, more configurable, and easier to debug.

1. **Lighter**
    * Remove [locale](https://github.com/vazco/meteor-universe-i18n/blob/9cf2126a1e0f58a3102810ff32ced38fb9af522e/source/locales.ts) and [currency data](https://github.com/vazco/meteor-universe-i18n/blob/d1c42ddc5cca8799dc61d87593b0f40ca55558c2/lib/locales.js#L360-L767). If needed, one can copy it from there.
        * We did not update this list for a long time and don't intend to.
        * This may require adjustments in the locale normalization as well as [translation file names resolution](https://github.com/vazco/meteor-universe-i18n/#translations-files).
    * Remove [React integration](https://github.com/vazco/meteor-universe-i18n/blob/d1c42ddc5cca8799dc61d87593b0f40ca55558c2/lib/i18n.js#L67-L135) (including the old [`getRefreshMixin`](https://github.com/vazco/meteor-universe-i18n/blob/d1c42ddc5cca8799dc61d87593b0f40ca55558c2/lib/i18n.js#L350-L362)). The important part here is to create a guide on using the package with React.
    * Remove [`createTranslator`](https://github.com/vazco/meteor-universe-i18n/blob/d1c42ddc5cca8799dc61d87593b0f40ca55558c2/lib/i18n.js#L137-L155) and [`createReactiveTranslator`](https://github.com/vazco/meteor-universe-i18n/blob/d1c42ddc5cca8799dc61d87593b0f40ca55558c2/lib/i18n.js#L163-L174) and create a short note on how to replace it.
    * Remove [`purify`](https://github.com/vazco/meteor-universe-i18n/blob/d1c42ddc5cca8799dc61d87593b0f40ca55558c2/lib/i18n.js#L211-L215) option.
    * Remove [`parseNumber`](https://github.com/vazco/meteor-universe-i18n/blob/d1c42ddc5cca8799dc61d87593b0f40ca55558c2/lib/i18n.js#L243-L257).
2. **More configurable**
    * Extract [string interpolation](https://github.com/vazco/meteor-universe-i18n/blob/d1c42ddc5cca8799dc61d87593b0f40ca55558c2/lib/i18n.js#L207-L209) into a separate, replacable function.
3. **Easier to debug**  
    * Simplify [`getTranslation` fallbacking mechanism](https://github.com/vazco/meteor-universe-i18n/blob/d1c42ddc5cca8799dc61d87593b0f40ca55558c2/lib/i18n.js#L193-L206).
        * Consider implementing a callback for missing translations instead of only the [`hideMissing`](https://github.com/vazco/meteor-universe-i18n/blob/d1c42ddc5cca8799dc61d87593b0f40ca55558c2/lib/i18n.js#L203) option.
4. **Future ideas**
    * Create and maintain a proper changelog from v2.0.0 on.
    * Setup CI process.
        * With automated publishing, if possible.
    * TypeScript-safe translations, especially for `getTranslation`.
        * Maybe with a runtime validation for missing translations?
    * Provide an integration with the [`Intl` API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl)?
    * Consider adding a proper support for pluraziation.

**Comment by Gwened** [comment]
Why would you want to remove the purify option?

Sometimes you want to translate some HTML texts.
Some use cases that come to mind:
- Email templates
-  Having <b></b> as part of text data to let writing emphasis some keywords.

The default purify function html-encodes data, so it's not usable as HTML: the tags appear as text.

Currently, you can use this trick to bypass it:
`    i18n.setOptions({purify: (s: string) => s});`
But that global setting is ugly, while, prior to v1.32, you could conveniently pass _purify=false to specific texts.

What do you intend to do regarding those use cases?

**Comment by radekmie** [comment]
Hi @Gwened and thanks for taking the time for feedback!

We want to remove this option, as it doesn't make sense to have _all_ translations purified. As you said, _sometimes_ you want to translate email templates or other potentially data-sensitive texts. In our opinion, you should sanitize (purify) the text explicitly, in your code, according to your own rules and requirements. If you need one, I strongly recommend the [`sanitize-html`](https://www.npmjs.com/package/sanitize-html) package - we do use it in several projects and it serves us very well. Just keep in mind that it's relatively large.

Additionally, [our current implementation](https://github.com/vazco/meteor-universe-i18n/blob/d1c42ddc5cca8799dc61d87593b0f40ca55558c2/lib/i18n.js#L377-L385) yields unnecessary performance impacts that could be avoided.

**Comment by Gwened** [comment]
Thanks, makes sense.
So from now on, I'll use the options to bypass it globally, and call my own purify fonction whenever dealing with user content or requiring to print HTML code.

**Comment by jasongrishkoff** [comment]
Hi, I can see there's a Readme for v2 somewhere, but I'm unable to access it. Can you bychance make this public?

**Comment by piotrpospiech** [comment]
> Hi, I can see there's a Readme for v2 somewhere, but I'm unable to access it. Can you possibly make this public?

Hi @jasongrishkoff, Readme was changed a little, but it is still available on the main page of the [Github repo](https://github.com/vazco/meteor-universe-i18n). Are you looking for something specific?

**Comment by jasongrishkoff** [comment]
From what I can see, one of the main changes is that you've removed `purify`, but the docs still reference is. Will it still work with this new version?

**Comment by piotrpospiech** [comment]
`purify` was removed. It won't work anymore. I will update Readme.

**Comment by jasongrishkoff** [comment]
Okay great. And the issue with `onChangeLocale` on `<T>` has also been resolved? Was poking through the code for a reference to this but didn't see it.

**Comment by piotrpospiech** [comment]
What issue are you referring to? Can you send me a link?

**Comment by dovydaskukalis** [comment]
2.0 RC1 does not work on Windows because of 2 test files ([meteor_practicalmeteor:sinon.d.ts](https://github.com/vazco/meteor-universe-i18n/blob/master/tests/meteor_practicalmeteor:sinon.d.ts) and [meteor_universe:i18n.d.ts](https://github.com/vazco/meteor-universe-i18n/blob/master/tests/meteor_universe:i18n.d.ts)) having a colon in the file name which is not allowed on Windows. Replacing it with _ fixes it but not sure if it affects anything else.

**Comment by piotrpospiech** [comment]
Hi @dovydaskukalis, thanks for your feedback. I fixed that in `v2.0.0-rc.2`

**Comment by piotrpospiech** [comment]
`v2.0.0` has been released!
