### ISSUE TITLE
Question : How to update client translations (strange cache)

### ISSUE THREAD

**Issue by dokithonon** [vazco/meteor-universe-i18n#147]
Hello, I am migrating from TAP to universe.
In our application, we change the translations and then we would like this to reflect on the client (blaze)
On the server the _translations object is updated well but not on the client.

<img width="738" alt="Screenshot 2021-12-24 at 10 23 16" src="https://user-images.githubusercontent.com/1856638/147339751-e91abe30-d0a9-4a40-9a2c-0b387dbcfff3.png">

And in the js file in head : 

<img width="574" alt="Screenshot 2021-12-24 at 10 25 56" src="https://user-images.githubusercontent.com/1856638/147339914-ae5e9b82-67d1-4d15-a268-de0bb3c839e4.png">

This work if we restart the server but this is not what we want

On the client, after the callback, I have tried to delete the js file in head then do addTranslation and also loadLocale but this has no effect.

How to you do this ? Thanks a lot.

**Comment by dokithonon** [comment]
I was able to make it works by removing the cache mecanism. Not sure if this is a good idea.

**Comment by zendranm** [comment]
Hi @dokithonon, I will look into it. Could you specify on which versions of the package and the meteor are you experiencing this?

**Comment by dokithonon** [comment]
Hello, thanks. I am using Meteor version 2.5.2 and package version 1.32.4.

**Comment by zendranm** [comment]
Hi @dokithonon, as this issue is probably related to the #148, I am closing it as there is no reproduction of the problem. I'll reopen it once there's a reproduction for it.
