### ISSUE TITLE
Easy to override options used by the library

### ISSUE THREAD

**Issue by ziarno7** [vazco/meteor-universe-i18n#15]
So today I noticed this little piece of code in my project:

```
_i18n.options = {
  open: '[',
  close: ']'
};
```
 
I was of course overriding the `_i18n.options` that are actually **used in the library** :) - not sure if it's just me, but imo you should either create a `setOptions` function that makes sure the the default options are still there, or just put the options into _i18n prototype, so that:

`_i18n.__proto__.options === options;`

this way, even if I were to override `_i18n.options`, the missing fields would be found in the prototype.

**Comment by cristo-rabani** [comment]
Hello,

I agree with you, we need do something with options.
Thanks for pointing this.
