### ISSUE TITLE
Is it possible to pass arguments to Blaze?

### ISSUE THREAD

**Issue by i-talic** [vazco/meteor-universe-i18n#150]
I installed the universe:i18n-blaze package and it works like a charm. But I can't find a way to pass an argument to the string. Am I correct that it's not supported?

**Comment by piotrpospiech** [comment]
Hi @i-talic,

For example, if your translation file looks like this:
```
exampleName: Example {$name}
```

You can pass an argument in the blaze template with the following code:
```
{{__'exampleName' name='John'}}
```

Did you mean something like this?

**Comment by i-talic** [comment]
Amazing, thank you! I tried different syntaxes but not this one .-)
