### ISSUE TITLE
I got raw html even with 3 curly brackets

### ISSUE THREAD

**Issue by davidjmz** [vazco/meteor-universe-i18n#153]
Hey, I migrated from Tap to Universe to get faster compilation and refresh times (BIG THANKS FOR THAT) and everything is working but the `{{{ __ 'string' }}}` to get a translation with HTML inside, I get the raw html, any solutions or work arounds to that? 

Thank you very much.

**Comment by zendranm** [comment]
@davidjmz just to clarify, this solution will also work with notation for [rendering raw HTML](http://blazejs.org/guide/spacebars.html#Rendering-raw-HTML). So for example if the translation looks like this:
```
i18n.addTranslation('en-US', 'tools.string', '<b>test</b>');
```
then `{{{__ '.string' _purify=false}}}` will return bolded `test` text.
