### ISSUE TITLE
about cache management

### ISSUE THREAD

**Issue by soolidtech** [vazco/meteor-universe-i18n#155]
Hello !
Thanks for sharing this great library !

i've created a sandbox here : https://github.com/soolidtech/test-i18n-cache

it looks like with this library, we have two possibilities for managing translations cache : 
- cached
- not cached (fresh opt set to true)

The thing is that cached setting makes it impossible to get new translation versions except if one clean his browser's cache.
Repro can be observed by cloning my repository `https://github.com/soolidtech/test-i18n-cache`

steps to reproduce :
`npm run start`
- change locale to french on app screen
- screen displays "Bonjour" => ok
- change content of `imports/i18n/fr/Test.i18n.yml` file with a new translation like "Bonjour Monde" and save
- refresh app screen
- change locale to french on app screen
- Content is still "Bonjour"

I don't want to use "fresh" neither since it's overkill

Could we consider using etag like Meteor team does in its docs about serving a static content ?
https://docs.meteor.com/packages/webapp.html#Serving-a-Static-Landing-Page

This way, cache would be invalidated if any translation changes

Thanks for reading

**Comment by zendranm** [comment]
Hi @soolidtech, thanks for your suggestion and for providing reproduction. For now ,our priority is to finalize release of version `2.0.0` so we will take care of it within the scope of this new version.
