### ISSUE TITLE
Package doesn't work on macOS

### ISSUE THREAD

**Issue by Kamran95** [vazco/meteor-universe-i18n#161]
meteor-universe-i18n is not working on mac OS
instead of returning the language string, it displays the key used to get that string from the config

The issue can be traced by visiting 
https://devwallet.pylons.tech/
on both mac and windows or ubuntu

**Comment by piotrpospiech** [comment]
Hi @Kamran95, thanks for your feedback.

https://devwallet.pylons.tech/ is unavailable. Can you also provide some code examples how did you configure `meteor-universe-i18n`?

**Comment by kienntk** [comment]
@piotrpospiech : I also get this issue. 
here is my configuration:

```
import i18n from "meteor/universe:i18n";

i18n.setLocale('en');
i18n.getLocale(); // en

console.log(i18n.getLanguages('en')); // this output is []
console.log(i18n.__("common", "userName")); //output is: common.userName
```

Here is my `en.i18n.json` file:

```
{
    "_locale": "en",
    "_namespace": "common",
    "userName": "User Name"
}
```
Looking forward to hearing back from you soon.
