### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by nicolamr** [vazco/meteor-universe-i18n#17]
Sometimes the UI is rendered before the translations (or the translations of a specific language) are loaded. This results in the page being only partially translated.

How do I make sure all translations are loaded before rendering a react component? Can I depend reactively on the translations?

**Comment by cristo-rabani** [comment]
Hello, 
There is many ways.
You can use promise what is returned by setLocale.
or use onChangeLocale(yourFn), or use refreshMixin.

**Comment by nicolamr** [comment]
What's the official way to check whether translations are not yet available?
If I check getLocale() it is already set before the translations are loaded.

What I want to do is:

    loaded = areTranslationsLoaded()

    i18n.onChangeLocale(function(locale) { loaded=true });

What to put instead of areTranslationsLoaded()

**Comment by cristo-rabani** [comment]
I recommend to add default language to bundle by using environment variable.
but if you can't you can show progress bar or something else to the moment
callback in i18n.Change Locale will be called. Also when you make setLocale a promise is returned, so you can use it.

Tell me where you need this information? Is that react js? or blaze?

**Comment by nicolamr** [comment]
I'm going to use the environment var for our main language. I'm now solving the issue for other languages.

The idea is to make a  react component that does what you say, but is independent of where I setlocale. Here's my approach:

    createComponent: ->
        getInitialState: ->
            translationsLoaded: ?
        componentDidMount: ->
            self = @
            i18n.onChangeLocale((locale) ->
                self.setState
                    translationsLoaded: true
        render: ->
            if @state.translationsLoaded
                ...
            else
                loadbar

**Comment by cristo-rabani** [comment]
```
i18n.setLocale('fr-FR').then(function () { loaded=true; })

// or if you want use with tracker.autorun you can use:
i18n._deps.depend(); // for establish reactivity
```

I can add method in universe:i18n-blaze package, so you will might do this in that way: i18n.isLoaded(locale)

**Comment by nicolamr** [comment]
I'm using that approach (for some reason i18n.setLocale() is returning nothing - I'm using version 1.3.7).

Anyway isLoaded would allow to do a more modular code decoupled from where/when setLocale is used.

**Comment by cristo-rabani** [comment]
I added for you method isLoaded(locale)

```
i18n.isLoaded('de-DE') 
```
It will give you information about state of loading locale in current moment,
 as a default is current language so parameter can be omitted.

**Comment by nicolamr** [comment]
Thanks a lot! Now there seems to be a bug (or the code behaves in a way different than expected):

    i18n.onChangeLocale ->
        console.log i18n.isLoaded()

logs false.

And even if I use UNIVERSE_I18N_LOCALES='de-DE'

i18n.isLoaded() is false at the beginning, even though exploring the object  i18n._translations["de-DE"] is actually set.

Based on this, my current version of the component is the following:

	Templates.Translations = React.createClass
		getInitialState: ->
			translationsReady: i18n.isLoaded() or i18n._translations[i18n.getLocale()]?
		componentDidMount: ->
			self = @
			i18n.onChangeLocale ->
				self.setState
					translationsReady: true
		render: ->
			if @state.translationsReady
				@props.children[0]
			else
				@props.children[1]
