### ISSUE TITLE
1.9

### ISSUE THREAD

**Issue by m-pokrovskii** [vazco/meteor-universe-i18n#174]
Is there any way to make a 2.0.0 version works with meteor 1.9? It does install  1.31.0 only. Thanks.

**Comment by piotrpospiech** [comment]
Hi @m-pokrovskii, I will check if `v2.0.0` works with Meteor `v1.9`, and if so, I will expand supported Meteor versions. However, due to Christmas break, I will do it next week.

**Comment by piotrpospiech** [comment]
`v2.0.1` works with Meteor `v1.9`
