### ISSUE TITLE
Remove usage of Fibers

### ISSUE THREAD

**Issue by dovydaskukalis** [vazco/meteor-universe-i18n#179]
Noticed that this module is using Fibers. Since Meteor is migrating away from it, what is the plan for this module? Seems to be used only here https://github.com/vazco/meteor-universe-i18n/blob/5c9f1c0a2d10155e4a529684c91118f40bf149e6/source/server.ts#L19

**Comment by zendranm** [comment]
Hi @dovydaskukalis, thank you for pointing it out. Turned out that Fibers weren't really necessary there so I removed it keeping the functionality the same.
