### ISSUE TITLE
React is not defined

### ISSUE THREAD

**Issue by MHerszak** [vazco/meteor-universe-i18n#18]
Hi,

it seems like React isn't defined in your _i8n file on line 66:

TypeError: Cannot read property 'PropTypes' of undefined at Object.createComponent (packages/universe:i18n/lib/i18n.js:66:27)

Regards,

**Comment by cristo-rabani** [comment]
Hi, 
You must pass React object as a last parameter of i18n.createComponent
``createComponent (translator = i18n.createTranslator(), locale, reactjs)``

Only if you use react-runtime or react package from atmospherejs this parameter can be omitted.

**Comment by MHerszak** [comment]
Sorry, you are right. const T = trans.createComponent(trans.createTranslator('accounts-ui'),'en',React);

I wasn't paying attention. What do you want me to do with local. Is that a must?

**Comment by cristo-rabani** [comment]
You can pass empty string like "" or just `undefined`

**Comment by MHerszak** [comment]
Thanks!

**Comment by cristo-rabani** [comment]
quicker:
```
const T = trans.createComponent('accounts-ui','',React);
```

**Comment by MHerszak** [comment]
What are the pros to set or not set local?
