### ISSUE TITLE
Problem with <T> component

### ISSUE THREAD

**Issue by dstuit** [vazco/meteor-universe-i18n#19]
When I'm trying to show translated message throw React component <T> I get an error in a console: 

> Warning: getInitialState was defined on T, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?

Anyway translated message is shown, but why this error may appear?

I use Meteor 1.3, React, "ecmascript" package. Here is my code:

```
import React from 'react';

const T = i18n.createComponent();

export default class Header extends React.Component {
  render() {
    return (
      <div>
        <T>test</T>
      </div>
    );
  }
}
```

**Comment by cristo-rabani** [comment]
Hello @dstuit 
Please replace line:
```js
const T = i18n.createComponent();
```
onto:
```js
const T = i18n.createComponent(i18n.createTranslator(), '', React);
```
And tell me if it helps.

**Comment by cristo-rabani** [comment]
In the next version, T component will be built as a inherited from React.Component instead of using React.createClass.

P.S. I found familiar issue in react repository: [#4214](https://github.com/facebook/react/issues/4214)

**Comment by dstuit** [comment]
Thanks for your answer.
I've replaced this line, but nothing changed.
By the way, anything works fine in my another app built with Meteor 1.3-rc.1 and Mantra.

**Comment by cristo-rabani** [comment]
done in universe:i18n@1.4.0
