### ISSUE TITLE
Changes to yml files not reflected in client

### ISSUE THREAD

**Issue by nmaro** [vazco/meteor-universe-i18n#20]
It might have to do with meteor 1.3... When I change yml file, only the server gets restarted. The client doesn't reload. Even when reloading the page, the translations are still the old ones. I had to explicitly open and reload /universe/locale/de-DE and then reload the client, to get the updated translations.

**Comment by cristo-rabani** [comment]
Hello,
Did you try to clear browser cache?
This package sets headers:
```
i18n.options.translationsHeaders = {'Cache-Control':'max-age=2628000'};
```
So, after reloading you should to have refreshed translations

Other thing is that
Hot code reload feature is not implemented for non-bundled locales.
So, if client doesn't have files to change, client version will not be reloaded.

Of course, 
we have in plan to add support this functionality.

**Comment by nmaro** [comment]
Btw. are you following the mantra development? You might want to jump in here: https://talk.mantrajs.com/t/internationalisation/34/8

**Comment by peterpetre** [comment]
This issue is still there. Any solution?

**Comment by cristo-rabani** [comment]
This, isn't exactly issue:

Two things: Cache-Control':'max-age=2628000'

- translation Headers 

-  hot code reload feature works only with [bundled locales](https://github.com/vazco/meteor-universe-i18n/#incremental-loading-of-translations)

**Comment by peterpetre** [comment]
Sorry first time using this package and i cant understand you clearly.

At the moment i run this code in client , i tried it in routes file too
```
import i18n from 'meteor/universe:i18n';

function getLang() {
    if (navigator.languages != undefined)  {
        return navigator.languages[0]
    }
    return navigator.language || navigator.browserLanguage
}
console.log(getLang())

i18n.setLocale('de').then(function () {
    console.log('already is!');
});
console.log(i18n.getLocale())
```

I run this in this server, i tried it in startup and out of it
`i18n.options.translationsHeaders = {'Cache-Control':'max-age=2628000'};`

I got two files one de.i18n.yml and one en.i18n.ymal in i18n file

and in react components i have like
`{i18n.__('app.title')}`

I tried too

```
launchctl setenv UNIVERSE_I18N_LOCALES all
launchctl setenv UNIVERSE_I18N_LOCALES 'en-US, de'
```

**Comment by cristo-rabani** [comment]
Hello, 
Could you explain what is going on in your example.
 - what is wrong ?
 - what is your expectation ?

Now, I can se that: 
```
import i18n from 'meteor/universe:i18n';

function getLang() {
    if (navigator.languages != undefined)  {
        return navigator.languages[0]
    }
    return navigator.language || navigator.browserLanguage
}

//this will show locale from browser (and nothing else):
console.log(getLang()) 

// here you set 'de' for i18n 
i18n.setLocale('de').then(function () {
    console.log('already is!');
});

// here you will see current locale but it can be executed before `i18n.setLocale('de')`
console.log(i18n.getLocale())
```
Universe i18n does not get automatically browser locale. You must set it manually:

```
import i18n from 'meteor/universe:i18n';

function getLang() {
    if (navigator.languages != undefined)  {
        return navigator.languages[0]
    }
    return navigator.language || navigator.browserLanguage
}

i18n.setLocale(getLang()).then(function () {
    console.log('already is!');
    console.log(i18n.getLocale())
});
```

**Comment by cristo-rabani** [comment]
Hi @nmaro, @peterpetre
In new version languages should be refreshed with hot code reload functionality

**Comment by macrozone** [comment]
on universe:i18n@1.9.0 caching problem is still there. Texts do not refresh on production
