### ISSUE TITLE
Uncaught ReferenceError: locales is not defined

### ISSUE THREAD

**Issue by fmilani** [vazco/meteor-universe-i18n#21]
The error occurs when I try to set the locale for my app on Meteor.startup(...). Precisely, it happens on api.js line 7, trying to get localeName on i18n.loadLocale method.

Does anybody has experienced this issue?

Thanks in advance

**Comment by justinFather** [comment]
same problem

**Comment by cristo-rabani** [comment]
Hello,
Should be fixed in version 1.4.1
