### ISSUE TITLE
Waiting for translations to be loaded

### ISSUE THREAD

**Issue by fmilani** [vazco/meteor-universe-i18n#23]
Hi,

How can I make my client code to wait until the translations for the user locale are loaded? I couldn't find it on the documentation and when I first access the app I can see the keys being displayed and only (shortly) after I see the translation being applied.

Thanks

**Comment by fmilani** [comment]
I managed to do so by using the onceChangeLocale method.

**Comment by stizzlestizzle** [comment]
Hi @fmilani 

I think I am facing a similar issue, I am trying to set a default language but sometimes it still falls back to english.

Can you explain how you did it? Thanks.

**Comment by fmilani** [comment]
Hello @stizzlestizzle ,

What I did was, on `client/main.js`:

```
import { Meteor } from 'meteor/meteor';
import { render } from 'react-dom';
import renderRoutes from '../imports/startup/client/routes.jsx';

...
Meteor.startup(() => {
  i18n.setLocale('pt-BR');
  i18n.onceChangeLocale(() => {
      render(renderRoutes(), document.getElementById('app'));;
  });
});
```
