### ISSUE TITLE
Possible for entries in YML file to refer to other YML vars?

### ISSUE THREAD

**Issue by ffxsam** [vazco/meteor-universe-i18n#24]
Is it possible to do something like this?

```yaml
deleteBtn: "Delete"
message: "Click the {$deleteBtn} button."
```

**Comment by radekmie** [comment]
Hey @ffxsam. No, YAML does not support variables, *but* it supports anchors. Here is an example of anchors from [`yaml.js`](https://github.com/jeremyfa/yaml.js/blob/develop/test/spec/YamlSpec.coffee#L673-L702) (this package uses it). Also, here's a link to a question on StackOverflow - there's a [good explanation](http://stackoverflow.com/questions/4150782/using-yaml-with-variables).
