### ISSUE TITLE
Use elements as string inside react component

### ISSUE THREAD

**Issue by gbhrdt** [vazco/meteor-universe-i18n#25]
```
<T name={<code>worker.js</code>}>workerFileDescription</T>
```

results in:

`Description asdasd [object Object] asdasd`

I think it would be better to allow elements inside strings.

**Comment by cristo-rabani** [comment]
Hello,

It seems as a good idea.
I think this can be added in next release

**Comment by cristo-rabani** [comment]
Hello, 

Check new version 1.10.0

Now you can do like that:

```jsx

<T _translateProps={['placeholder']}>
      <FormControl type='text' placeholder='search' />
</T>
```

**Comment by gbhrdt** [comment]
Looks good, thanks!
