### ISSUE TITLE
getLanguages API

### ISSUE THREAD

**Issue by mquandalle** [vazco/meteor-universe-i18n#27]
The TAPi18n has an API method, `getLanguages`, to get the list of languages for which there exist translations. This method is useful to display UI menus to change the language. It doesn’t seem that this package implements a similar method, did I miss something?

**Comment by radekmie** [comment]
No, there's no public API for it. As for now, you can use `i18n._locales` ([it looks like this](https://github.com/vazco/meteor-universe-i18n/blob/master/lib/locales.js#L1)), but it seem reasonable, to make public API for it.

**Comment by mquandalle** [comment]
To be clear, the goal of the desired API isn't to return all `i18n._locales` keys, but only the ones for each there is a registered translation.

**Comment by radekmie** [comment]
Yes, of course. I thought about `getLanguages(code = true)`, which will return either `['de', 'en', ...]`, or `['Deutsch', 'English', ...]`.

**Comment by radekmie** [comment]
Copied from README.md:

```js
// Getting languages with at least one translation
i18n.getLanguages(codes = true, native = false)
i18n.getLanguages() // ['de', 'en']
i18n.getLanguages(false) // ['German', 'English']
i18n.getLanguages(false, true) // ['Deutsch', 'English']
```

**Comment by MacRusher** [comment]
Maybe instead of 
`i18n.getLanguages(false, true)`
we should have
`i18n.getLanguages({codes: false, native: true})`

It's more readable without checking the docs which positional flag means what and it's also more future-proof.

**Comment by radekmie** [comment]
I've also thought about `index` ([that's why](https://github.com/vazco/meteor-universe-i18n/blob/master/lib/locales.js#L2)), but obejct also looks OK.

**Comment by mquandalle** [comment]
The API isn’t working as intended. The goal of this `getLanguages` method is to display a list of available languages so that the user could change the current language. However the current method only returns languages that are already downloaded on the client—instead of all available languages—which mean that if you are using the default English language you won’t see any other choice in the language picker—are there isn’t any language downloaded.

I also agree that the boolean parameters are confusing, from a reader point of view `.getLanguages(false, true)` doesn’t make much sense. I would say that it is better to keep the method simple, and have it only return the language codes (like the first example). If method consumers want to get the full names instead, they can use a simple mapping:

```es6
import { getLanguages, getLanguageName, getLanguageNativeName } from 'meteor/universe:i18n';

getLanguages() // ['de', 'en']
getLanguages().map(getLanguageName) // ['German', 'English']
getLanguages().map(getLanguageNativeName) // ['Deutsch', 'English']
```

In the example where I want to display a language picker, which I believe is quite common, I need both the language “code” as this is language identifier string used internally and the language name as the name to display in the UI, so I would use something like:

```js
getLanguages().map((code) => ({
  code,
  name: getLanguageNativeName(code),
})
```

**Comment by MacRusher** [comment]
I've just published 1.8.1 with updates to `getLanguages`.
Technically this is a breaking change but it's more like a patch :) You current `getLanguage` invocation will return empty array if you use extra params discussed above.

I've also updated docs with your use case as I also believe that this is quite common usage.

Downside is that you need to fetch data from the server, but this shouldn't be a big problem.

I was thinking about building such method into i18n API but decided not to (unneeded extra api surface, and requirements for this method will probably vary for different people anyway so DIY approach makes more sense to me).

From new docs:

You can use `i18n.getLanguages` to list all languages with at least one translation:
```javascript
i18n.getLanguages() // ['en', 'de']
i18n.getLanguages('name') // ['English', 'German']
```

This method will show all available translations on the server but only loaded translations on the client.

To build a language picker with all possible options you would need to fetch data from the server, e.g. by a method:
```javascript
Meteor.methods({
    getLanguages() {
        return i18n.getLanguages().map(code => ({
            code,
            name: i18n.getLanguageNativeName(code)
        }));
    }
});
```

**Comment by mquandalle** [comment]
The original point of this feature request was to have a method that returns the list of all available languages. I named it `getLanguages` because that’s how `meteor/tap:i18n` named it, but if you want to only return downloaded language with `getLanguages`, then my request become to have a `getAvailableLanguages` (or similar) that would return them all.

The Meteor method solution isn’t very satisfying because it requires the developer to write some plumbing for the data transmission that could be better handled by the package, and because requiring a client-server roundtrip is pretty slow and we would need some clever logic to do it before rendering the language picker and cache the result. In most application, the set of existing translations doesn’t change at runtime, so it would be enough to send a list of available languages in the initial HTTP response without relying on DDP.

The Meteor plugin API doesn’t make the implementation super intuitive, but it still reasonably easy. We’ll have to subclass the `processFilesForTarget(inputFiles)` method that receive the whole list of matching files, and then after the the super method is called as usual just publish a JS file to the client that contains the list of all available language code; something like:

```es6
class UniverseI18nBuilder extends CachingCompiler {
  processFilesForTarget(inputFiles) {
    super(inputFiles);

    const locales = inputFiles.map(this._getLocaleFromFileName);
    inputFiles.addJavaScript({
      path: 'languageList.js',
      data: `Package['universe:i18n'].i18n.availableTranslations(${JSON.stringify(locales)})`,
    });
  }
}
```

Does that makes sense to you @MacRusher?

**Comment by MacRusher** [comment]
Your solution with build plugin has one downside - it would only work for translations made using yml/json files. Unfortunately this is not the only way to add translations, as they can be also added dynamically via `i18n.addTranslation`. Just made a quick office survey and this is quite ofter used method. And they can change at runtime (e.g. loaded from the database)

At the moment I don't see an option for client to get list of all languages other than asking the server.
But I'm open for discussion.

I see three scenarios:
a) Developer use his preferred way to get this data from client to server and keep it up to date. This is the DIY approach that I describe in the docs using `Meteor.methods`, but this could also be a publication, Apollo resolver or whatever. I agree it's not perfect.
b) I can build this method call into `getLanguages` api so it's hidden from the developer. But then it would take a callback (yuck) or return a promise (less yuck). I'm also not a big fan of packages creating Meteor methods/publications unless it is necessary.
c) i18n could create a publication and subscribe to it. Client side `getLanguages` could be a reactive data source and return always correct list of languages. This could be also achieved using (a) but I agree that this is some extra boilerplate that could be hidden from the developer. But this also doesn't solves the problem, just sweep it under the rug.

@mquandalle do you maybe have some other ideas?
