### ISSUE TITLE
Meteor 1.4: more examples using classes, mixins, etc.

### ISSUE THREAD

**Issue by yanickrochon** [vazco/meteor-universe-i18n#28]
There should be more examples for ES6/2015 syntax using mixins. For example, what is the equivalent of

```jsx
import {refreshOnChangeLocaleMixin} from 'meteor/universe:i18n';

export default React.createClass({
    displayName: 'StatsWidget',
    mixins: [refreshOnChangeLocaleMixin],
    /* ... */
});
```

with declarations such as

```jsx
import { Component } from 'react';

export default class Foo extends Component {
  render() {
    return <div>Foo</div>
  }
}
```

**Comment by radekmie** [comment]
There's currently no built-in way, but you can achieve it in many different ways. Just to name few:

0. Create a [HOC](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html) for it _(preferred)_.
0. _Inline_ it _(6 LOC, really)_.
0. Use [react-mixin](https://github.com/brigand/react-mixin) _(not suggested)_.

If you need any help, just comment here.
If you would like to see more ES6 concerned documentation - also comment here.

**Comment by axelvaindal** [comment]
I have pretty much the same issue as above, and I don't understand how HOC could resolve my problem.

For example, I have a text input component, composed with a label and the actual text input html 5 tag.
Here is the sample:

```
/*
|--------------------------------------------------------------------------
| TextInput Component
|--------------------------------------------------------------------------
|
| This file defines a TextInput Component to be used.
| TextInput Component is defined as a Base Component. 
|
*/

import React, { Component, PropTypes } from 'react';
import classnames from 'classnames';

export default class TextInput extends Component 
{
    /**
    * constructor
    * This function is used in order to build the component. 
    * @param {PlainObject} [props] React Component Properties.
    */
   
    constructor(props) 
    {
        super(props);
    }

    /**
    * getComponentClassnames
    * This function is used in order to get component classes.
    * @return {Array} [cn] Classnames to apply.
    */
   
    getComponentClassnames()
    {
        const cn = ['component', 'text-input'];

        return cn;
    }

    /**
    * render
    * This function is used in order to render the component.
    * @return {HTMLEntity} [showcase] HTML to be displayed. 
    */
   
    render() 
    {
        const cn = classnames(this.getComponentClassnames().concat(this.props.classNames));

        let textInput = 
        <div className={cn}>
            <label htmlFor={this.props.id}>
                {this.props.label}
            </label>
            <input 
                id={this.props.id}
                type="text"
                name={this.props.name}  
                placeholder={this.props.placeholder} 
                required={this.props.required}         
                disabled={this.props.disabled}
                defaultValue={this.props.defaultValue}
            />
        </div>;
        
        return (textInput);
    }
}

TextInput.propTypes = 
{
    id:           React.PropTypes.string,
    name:         React.PropTypes.string.isRequired,
    label:        React.PropTypes.string,
    placeholder:  React.PropTypes.string,
    required:     React.PropTypes.bool,
    disabled:     React.PropTypes.bool,
    defaultValue: React.PropTypes.string,
};

TextInput.defaultProps = 
{
    id: "default",
    name: "Default Input",
    label: "Text Input",
    placeholder: "",
    required: false,
    disabled: false,
    defaultValue: "",   
};
```

This works fine, and there is no issue about it, it's pretty standard react code.
However, I would like to give the label property a **translated value**, and I don't understand how I am able to do that in a reactive way.

See, I can use (which is working fine btw):

```
<TextInput label={i18n.__('string.to.translate'} />
```

But this is not reactive, and when I change the current language inside my top component, this nested component is not updated as well.

Am I misunderstanding something or is there any workaround ?

Btw, I have the latest version of universe-i18n and the mixin doesn't exist in my environment (import keeps coming empty). I however have a getRefreshMixin function inside the source, but I don 't understand how to work with it.

![image](https://cloud.githubusercontent.com/assets/11026659/18134319/3fa3c3ae-6f9e-11e6-971c-37fbc147fc17.png)

**Comment by radekmie** [comment]
Hi @axelvaindal.
It would be better for your `TextInput` to stay as it is and just pass already translated string to it (as it is right now). That mixin is supposed to work as a React [mixin](https://facebook.github.io/react/docs/reusable-components.html#mixins).

But let's make it clear.

If your parent component (you've said, that you've _changed the current language_ there) has a state, then you can do it like this:

```js
class ParentComponent extends Component {
    constructor () {
        super(...arguments);

        this.state = {
            locale: i18n.getLocale()
        };

        this.onLocale = this.onLocale.bind(this);
    }

    onLocale (locale) {
        this.setState({locale});
    }

    componentWillMount () {
        i18n.onChangeLocale(this.onLocale);
    }

    componentWillUnmount () {
        i18n.offChangeLocale(this.onLocale);
    }

    render () {
        return (
            <section>
                {/* ... */}
                <TextInput label={i18n.__('string.to.translate')} />
                {/* ... */}
            </section>
        );
    }
}
```

When `i18n` locale will change, then we'll update `ParentComponent` state, so it will render again with the new locale.

Maybe I'll add it to the README?

**Comment by axelvaindal** [comment]
Hi @radekmie,

I will try what you propose tomorrow, I haven't tried it this way but it seems pretty logic seeing your code indeed.

I think it would be a good idea to add it to the README as well, considering I was thinking I add to refactor all my components in order to work with the <T> translation component.
I'm glad it was just a misunderstanding of mine, but maybe some other people have trouble with the ES6/2015 syntax and this would help them understand the situation :).

Just a question tough, if I use the state in my top layer component (for example my layout) in order for it to handle i18n state, onChangeLocale event will propagate through each nested component right, no matter the depth or do I need to use it in the direct HOC ?

**Comment by yanickrochon** [comment]
I'll try that as well.

**Comment by yanickrochon** [comment]
BTW: this is what I came up with, following `TrackerReact`'s implementation

```jsx
import { Component } from 'react';
import i18n from 'meteor/universe:i18n';


export default class LocalizedComponent extends Component {
  constructor() {
    super(...arguments);

    if (!this.constructor.prototype._isLocalized) {
      this.constructor.prototype._isLocalized = true;

      let superComponentDidMount = this.constructor.prototype.componentDidMount;
      let superComponentWillUnmount = this.constructor.prototype.componentWillUnmount;

      this.onLocale = this.onLocale.bind(this);

      this.constructor.prototype.componentDidMount = function (...args) {
        if (superComponentDidMount) {
          superComponentDidMount.call(this, ...args);
        }

        i18n.onChangeLocale(this.onLocale);
      };

      this.constructor.prototype.componentWillUnmount = function (...args) {
        if (superComponentWillUnmount) {
          superComponentWillUnmount.call(this, ...args);
        }

        i18n.offChangeLocale(this.onLocale);
      };
    }
  }

  onLocale() {
    this.forceUpdate();
  }
}
```

So, just use like `class Foo extends LocalizedComponent { ... }`

**Comment by radekmie** [comment]
@axelvaindal
I'm planning to add an `<LocaleProvider />` component. It will look like this:

```js
<LocaleProvider>
    <section>
        <section>
            <section>
                <T>no.matter.what.i.am.reactive</T>
            </section>
        </section>
    </section>
</LocaleProvider>
```

@yanickrochon
To be honest, I don't like your approach. Overriding methods is not a good idea.

**Comment by axelvaindal** [comment]
@radekmie I'd rather not use specialized component in order to translate my content.
I try to make my application less dependent of package in order to be able to reuse components more efficiently.
I'm afraid that using this kind of component will bind my application with your i18n package and make an eventual migration (for example, if the project is being abandoned for any reason) much harder.

I was more looking of a way of give translated string through each of my component with a top layer component handling the general localization state of the application.
I'll try to use your first answer this morning in order to know if this fits my need, and give you feedback about it :).

**Comment by radekmie** [comment]
@axelvaindal I don't think it bound your app to this package - it will be easy to remove this wrapping component and you can easily translate `<T>x</T>` to `{other_i18n('x')}` (even using regular expression).

**Comment by axelvaindal** [comment]
@radekmie May be you're right, although I need to try this before making any decision.

However, I think your idea of adding a `<LocaleProvider>` is a good idea in order to encapsulate the whole application.

Thank you for your explanations and your time :).

**Comment by radekmie** [comment]
@axelvaindal Well... _Work smart, not hard_... I've just recalled, that `<T />` is [automatically connected to the locale change](https://github.com/vazco/meteor-universe-i18n/blob/master/lib/i18n.js#L111-L117), so basically `<T>anything</T>` is already listening to locale change.

**Comment by axelvaindal** [comment]
@radekmie Yeah that's right, but I cannot pass the `<T/>` to my `InputText label`, so I have to put it inside the `InputText` component which was my initial problem for hard dependency (or I can use your previous response).

**Comment by radekmie** [comment]
You can use `<T />` as a label, but you have to change the `propTypes` to `node`.

**Comment by axelvaindal** [comment]
So, I just tried your first response in order to make some test.
It seems this is only working in the direct top component, but not in the top layer component.

I have a Layout component, Index page component and a LoginModal component and I wished to translate the top title of the modal.
If I put your code inside the login modal, this is working fine and it's reactive on locale change.
If I put your code inside the index page component, this is working fine as well.
If I put your code inside the layout component, this doesn't work anymore. More precisely, the locale is well changed but the child component isn't rendered again (thus I can't see the top title being translated on change).

I assume this was the expected behaviour ?

If so, it is actually a problem because I will have to duplicate my code all over my components in order to keep track of i18n onLocaleChange, which is not very optimized nor well organized code :/.

**Comment by radekmie** [comment]
So go ahead and use `<T />` - that's what it is for.

**Comment by yanickrochon** [comment]
@axelvaindal there is nothing wrong with overriding methods. `this.someMethod = this.someMethod.bind(this);` is a common pattern in React and is perfectly fine. If the method is not working as expected, for some reason, it is most likely because something is not using it right.

The pattern of keeping a backup of the original method, then redefining it is also consistent with JavaScript coding practices, where a function behaves just as a variable. It actually make things quite transparent with very minimal impact on the original implementation (no need to call super), and allow a certain degree of freedom where the actual implementation is "injectable".

I personally rather extend a `LocalizedComponent` where I can substitute the implementation at any time, than wrapping my UI components with various other wrapper components. As you said, wrapping the entire app does not work, and you *need* to wrap the localized components only, individually, anyway, thus requiring creating even more components; my `LocalizedComponent` just does that with very minimal code change, using exactly the same amount of components, with minimal efforts to refactor if needed.

**Comment by axelvaindal** [comment]
@yanickrochon I'm not the one talking about overriding. I tag @radekmie for him to see your answer :).

**Comment by yanickrochon** [comment]
@axelvaindal d'oh! my bad :)

@radekmie then my last comment is addressed to you :stuck_out_tongue:

**Comment by radekmie** [comment]
@yanickrochon I don't like it, because it's _hurting my inheritance sense_. As you've said: 

> no need to call super

You **should** call `super`, because it's your parent class method - this _reversed inheritance_ is just bad.

**Comment by yanickrochon** [comment]
@radekmie if you take the conventional OO paradigm, then yes. However JavaScript is prototypal, not object oriented. Many developer make the same confusion. The need to call `super` on inheritance is a requirement of that standard, and is gradually being replaced by the [dependency injection (DI)](https://en.wikipedia.org/wiki/Dependency_injection), which is a well-tested design pattern that offers a lot more than the standard OO model.

In my case, I am using a base class as I found

```
class Foo extends TrackerReact(LocalizedComponent) { ... }
```

better than

```
class Foo extends TrackerReact(LocalizedReact(Component)) { ... }
```

For some components, I even replace all `<T />` with a single `LocalizedComponent` using the direct `i18n.__` method as it is more efficient and concise this way. I am not saying that the `<T />` component is irrelevant, but that it's use is not always ideal; wrapping each translation strings is not always ideal.

The point is that there already is a localized component (`<T />`) for individual strings, and DI is a better choice of wrapping an entire component than mingling with one's layout. IMO.

**Comment by radekmie** [comment]
I know, how it works. I know what it is. I 100% get you. I just don't like it. Be cool :+1:

**Comment by yanickrochon** [comment]
I was just replying to your statement :

> You **should** call super, because it's your parent class method - this *reversed inheritance* is just bad.

Because DI is not bad, it *is* a design pattern (i.e. not an anti-pattern).

**Comment by radekmie** [comment]
I've just never seen DI by inheritance.

**Comment by yanickrochon** [comment]
I tried implementing an interface (i.e. `@Localized`) but the support for it is awkward... and I didn't manage to make it work. Whereas `TrackerReact` works great! :smile: The end result is quite the same anyway.
