### ISSUE TITLE
Getting error in the translation file without declared "_locale"

### ISSUE THREAD

**Issue by newsiberian** [vazco/meteor-universe-i18n#3]
Hello,
while testing this module I've getting error like this:

>Your app is crashing. Here's the latest log.
>
>Errors prevented startup:
>
>While building the application:
><runJavaScript-63>:43:21: Cannot call method 'toLowerCase' of undefined (compiling both/i18n/en.i18n.json) (at handler)
>
>Your application has errors. Waiting for file change.

en.i18n.json:
```
{
  "pageNotFound": "Page not found!"
}
```
in case:
```
{
  "_locale": "en",
  "pageNotFound": "Page not found!"
}
```
...all work's fine, but you specified in the documentation:
>...Other ways file should have name of his locale or be in directory under this name:

Also I noticed that the translation does not pick up the browser locale. Is this fine?

**Comment by cristo-rabani** [comment]
Hello,

Thanks you for reporting this bug. 
In 1.0.2 is fixed. 

If you want get language from browser you can do it like this:

```js
// somewhere in page layout ( or in router?)
function getLang() {
    if (navigator.languages != undefined)  {
        return navigator.languages[0];
    }
    return navigator.language || navigator.browserLanguage;
}

i18n.setLocale(getLang());
```

This should work on client side but on server you must read from header 'accept-language'
