### ISSUE TITLE
Component <T> returns span

### ISSUE THREAD

**Issue by nazarposhta** [vazco/meteor-universe-i18n#31]
Hello! 
Do you know why (sometimes) component `T = i18n.createComponent()` returns value inside `<span>` tag?
Although my en.i18n.json file is clear (text only)

**Comment by radekmie** [comment]
Basically, it always return `<span>translated text</span>`.
If you want to omit it, then use `getTranslation` _(or `createTranslator`)_ directly.

Did I answered you?

**Comment by bompi88** [comment]
Is it possible to provide the type of DOM element which will be used when using `i18n.createComponent()`. For instance:

```js
createComponent (translator = i18n.createTranslator(), locale, reactjs, type='span') {

  ...

  return reactjs.createElement(type, {
    dangerouslySetInnerHTML: {
      __html: translator(children, params)
    }, key: this.state.systemlocale
  }); 

```

A typical usecase would be for `<h1>` tags and so on.

**Comment by radekmie** [comment]
Okay, now I get you. Do you want to create PR for this?

**Comment by bompi88** [comment]
Of course. To confirm: I'll add it as the fourth argument? Maybe consider the function to take an options object in later major release?

**Comment by radekmie** [comment]
Right now just add next argument. I'm planing complete rewrite of this package in the closest future and then I'll take care of this.

**Comment by bompi88** [comment]
Sure 😄 Created a PR with two additional suggestions #32. Just cherry-pick what you think suits this package. Hope it will meet your standards 👍
