### ISSUE TITLE
Confused about translation files

### ISSUE THREAD

**Issue by kaidoj** [vazco/meteor-universe-i18n#33]
Hei.
Im really confused how this should work with translation files.
Translation file is working with en-US.
I am setting i18n.setLocale('ru-RU') in imports/api/client/routes.js
I have folder lib/translations/ru-ru/pages.i18n.json
Then i even made folder to public/translations/ru/pages.i18n.json
pages is the _namespace.
Contents of the pages.i18n.json file.

```
{
  "_locale": "ru",
  "_namespace": "pages",
  "default_title": "bla bla",
  "default_description": "bal bla"
}
```

Im setting custom urls and path etc.

```
i18n.setOptions({
  hostUrl: 'http://test.example.com:3000/',
  pathOnHost: 'translations/'
});
```

I see in my source that i have scripts tag in head with url http://test.example.com:3000/translations/ru
but this should not be right.

Am i missing something?

**Comment by kaidoj** [comment]
Bump

**Comment by cristo-rabani** [comment]
Hello,

`_locale` and `_namespace` are the magical keys (`_locale` overrides locale from path), if you use them you can have name as you want like: `/trans/some.i18n.yml`

`.i18n.yml` files should be in application (between js files) not in public directory.

If you want load files from public directory you should compile them to `js`
