### ISSUE TITLE
hasTranslation

### ISSUE THREAD

**Issue by nmaro** [vazco/meteor-universe-i18n#34]
Hello, what is the best way to check whether a translation exists?
At the moment I'm using
__(x) !== x
which is not so nice ;)

**Comment by cristo-rabani** [comment]
Hello,

For now, there isn't an function like i18n.has('job.attachAFile'), but temporarly you can use UniUtils.has() like: 
```
UniUtils.has(i18n.getTranslations('en', null), 'job.attachAFile')
```
