### ISSUE TITLE
Working example code?

### ISSUE THREAD

**Issue by sonicviz** [vazco/meteor-universe-i18n#38]
Is there a working example of this project anywhere, with at least two languages demonstrating language file use? Seems to be the fastest way to understand how it pieces together.

**Comment by cristo-rabani** [comment]
Hello,

Good point, We can prepare such boilerplate in free time.

**Comment by sonicviz** [comment]
I figured it out eventually and got it working (nice package btw, ty!) but I think having a good working example will save people time and also "sell" the package better.

**Comment by ydc223** [comment]
Would you mind sharing your working version? As you mentioned that would be the best way to help understand how it all works togeher

**Comment by sonicviz** [comment]
I've been talking to MeteorChef about writing a recipe demonstrating integrating it into his Base boilerplate. I'll ping him and see if he's still interested.

**Comment by sonicviz** [comment]
Here's a write up of my example and there's a link in the article to the github repo: http://www.sonicviz.com/wp/2016/10/23/internationalizing-meteor/

**Comment by cristo-rabani** [comment]
Sonicviz,
We added link to your tutorial to our readme.md
It great job, thank you very much for your contribution for this package
