### ISSUE TITLE
getLang(): not all locales allowed

### ISSUE THREAD

**Issue by newsiberian** [vazco/meteor-universe-i18n#4]
Hello again,

I have an error in Chomium which shows me the following locales list:
> navigator.languages: Array[4]
>0: "ru-RU"
>1: "ru"
>2: "en-US"
>3: "en"
error:
![screenshot_9](https://cloud.githubusercontent.com/assets/11130487/9873119/1c597304-5bb7-11e5-89f0-a928e9fea4f7.png)

with something like this all works fine:

```
function getLang() {
	if (navigator.languages != undefined)  {
		if (typeof navigator.languages[0] === 'string') {
			return ~navigator.languages[0].indexOf('-') ?
				navigator.languages[0].replace('-', '_') :
				navigator.languages[0];
		}
	}
...
```

**Comment by cristo-rabani** [comment]
Hello, 

I added support for formats like yours 'ru-RU'
