### ISSUE TITLE
isLoaded is true even if translation is not yet loaded.

### ISSUE THREAD

**Issue by macrozone** [vazco/meteor-universe-i18n#41]
I have the situation where isLoaded is true, but the translator still returns the default translation (english).

I have this test snippet, that is called somewhere in a container:

```
console.log(i18n.isLoaded('de'), i18n.getTranslation('my.translation)); // returns true, "english translation"
  i18n.onceChangeLocale(() => {
    console.log(i18n.isLoaded('de'), i18n.getTranslation('my.translation')); // returns true, "german translation"
  }
```

it's hard to track this down, but i got similar results when using

```
i18n.setLocale("de").then(function(){
  i18n.getTranslation("my.translation"); // sometimes also returns english translation
});
```

The promise here should be resolved when the language is ready, but sometimes its resolved earlier.

**Comment by stizzlestizzle** [comment]
I'm late to the party but am facing similar issues.

@macrozone did you find a way to sort that out?

**Comment by cristo-rabani** [comment]
Hello,
Please check if Meteor.defer does not fix your problem.
I am going to check this case as soon as possible

**Comment by stizzlestizzle** [comment]
Any progress on this?

Let's say my default lang is "de".

```
i18n.setLocale(defaultLanguage);
i18n.getLocale();
```

(Also tried using the promise as above)

This will sometimes work and display "de" but sometimes not and fall back to "en".

Interestingly on mobile (iOS Safari) the error occurs almost every time whereas it does occur much less on the desktop.

**Comment by fadomire** [comment]
+1

**Comment by ixdi** [comment]
Maybe you have a number in the translation file.
```json
"32": "My translation",
```
To us the translation fails if there is a number.

**Comment by MacRusher** [comment]
Probably a race condition problem.
I'm closing the issue because it's stale. Please if it's still relevant.
