### ISSUE TITLE
Server-side i18n using Locale Defined by Client

### ISSUE THREAD

**Issue by jantrienes** [vazco/meteor-universe-i18n#43]
I want to use this package for both client-side as well as server-side i18n. Client side internationalization and switching between locales works just fine. 

However, i18n on server-side is causing some issues:

We were able to retrieve the `accept-language` from the HTTP headers by using the [headers package](https://atmospherejs.com/gadicohen/headers). 

Our application contains something along these lines:

``` javascript
if(Meteor.isServer) {
  var self=this;
  console.log('server headers: ');
  console.log(headers.get(self)['accept-language']); // yields en-us which defaults on my machine
}
```

The locale in the header is always en-us which is the default on my machine. Even if the client switches the language (via `i18n.setLocale()`) this value remains unchanged. 

How would we implement the server-side i18n and “notify” the server once the client changes its locale? Error messages by the server and form labels (provided by [vazco/uniforms](https://github.com/vazco/uniforms)) should be translated.

**Comment by cristo-rabani** [comment]
Hello, 

There is function `i18n.runWithLocale(locale, func)`, 
Any default locale in this function will be set from first parameter of this function.


```js
Meteor.methods({
   doSomething () {
       const {httpHeaders = {}} = this.connection;
       const acceptLanguage = httpHeaders['accept-language'] || 'en-US';
       return i18n.runWithLocale(acceptLanguage, () => {
                 //In this scope everything should have 'acceptLanguage' as a default.
                 throw new Meteor.Error('testErr', i18n.__('translation.of.error');
       })
   }
})
```

**Comment by jantrienes** [comment]
I tried your code, and I'm able to get the `accept-language` out of the header. 

However, this value always remains `en-US`, no matter what language has been set on the client with `i18n.setLocale()`. How can the client pass his current language as part of the request? Shouldn't the content of `accept-language` always be the value of `i18n.getLocale()`? 

**Client Component:**
```javascript
const T = i18n.createComponent();
i18n.setLocale('en-US');

export default class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      hideCompleted: false,
      locale: i18n.getLocale()
    };

    this.onLocale = this.onLocale.bind(this);
  }

  onLocale (locale) {
    this.setState({locale});
  }

  componentWillMount () {
    i18n.onChangeLocale(this.onLocale);
  }

  componentWillUnmount () {
    i18n.offChangeLocale(this.onLocale);
  }

  switchLocale() {
    if(i18n.getLocale() === 'en-US') {
      i18n.setLocale('de-DE');
    } else {
      i18n.setLocale('en-US');
    }
  }

  handleSubmit(event) {
   ...
    Meteor.call('tasks.insert', text);
   ...
  }

  render() {
    return (
      <div className="container">

        ...

        <li onClick={this.switchLocale.bind(this)}><T>ui.language</T></li>
      </div>
    );
  }
}
```

**this.connection (on server method)**
```
{  
  id:'nmavDFXZ37pXroqmq',
  close:[  
    Function:close
  ],
  onClose:[  
    Function:onClose
  ],
  clientAddress:'127.0.0.1',
  httpHeaders:{  
    'x-forwarded-for':'127.0.0.1',
    'x-forwarded-proto':'ws',
    host:'localhost:3000',
    'user-agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50'
  },
  headers:{  
    'x-forwarded-proto':'http',
    'x-forwarded-port':'3000',
    'x-forwarded-for':'127.0.0.1',
    'accept-encoding':'gzip, deflate',
    'accept-language':'en-us',
    referer:'http://localhost:3000/',
    'user-agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50',
    accept:'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'upgrade-insecure-requests':'1',
    connection:'keep-alive',
    cookie:'__utma=111872281.103641498.1472653055.1472653055.1472655148.2; __utmz=111872281.1472653055.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)',
    host:'localhost:3000',
    'x-ip-chain':'127.0.0.1,127.0.0.1'
  },
  headerDep:{  
    _dependentsById:{  

    }
  }
}
```

**Comment by cristo-rabani** [comment]
Hello, 

As I can see wright now:
The `accept-language` is placed in `headers` not in `httpHeaders` - please change it in my code.

Take care that the client must pass `accept-language` header, somehow to ddp request (And here I cannot help you)

Alternative way is keeping current locale on user document and updating this property any time when locale will be changed.

**Comment by jantrienes** [comment]
Thanks for your advice. I ended up using the user document for storing the current locale. 

Retrieving a translation on the server is now being done like this:
`i18n.__('notAuthorized', { _locale: Meteor.user().profile.locale })`

I'm using the `params` parameter of the `getTranslation` method, in order to avoid calling `i18n.setLocale()` with the proper locale first. Is this the preferred way of doing this? If so, should the documentation be refined with an example of how to use the `i18n.getTranslation(namespace, key, ... params`?

**Comment by yanickrochon** [comment]
I have a similar problem, where the client's language is "fr" but any method called, and executed on the server reports "en-US" for that request. It would be nice to have locales sync between client and server automatically.

**Comment by cristo-rabani** [comment]
@yanickrochon, 
Technically this is possible by attaching property to proper connection object on server side, but It is too hacky for current architecture of meteor to be implemented as a part of this package

**Comment by cristo-rabani** [comment]
New version synchronises client with locale used in server methods
