### ISSUE TITLE
Client side loadLocale call is not triggering server side loadLocale

### ISSUE THREAD

**Issue by Szauren** [vazco/meteor-universe-i18n#44]
Hi,
Maybe I misunderstood "remote loading of translations from different host" feature.
I would like to store translation files on remote http file server. Now when client part is calling meteor server for translation server part is just checking cache for it but is not querying http file server. Is it intended behaviour ?

**Comment by cristo-rabani** [comment]
Hello ,

Answer is yes and you can determine how long by headers
```
i18n.setOptions({
    // (On server side only) Gives you possibility of adding/changing response headers
    translationsHeaders = {'Cache-Control':'max-age=2628000'}
});
```

If you need to store files remotely you should store them as a pre compiled js files or by meteor that will be served files for you. 

pre compiled js file should look like: http://localhost:3000/universe/locale/en
