### ISSUE TITLE
multiple _namespace

### ISSUE THREAD

**Issue by soyJSus** [vazco/meteor-universe-i18n#46]
Hello good evening, as you would to create multiple _namespace in my .i18n.json ?

**Comment by cristo-rabani** [comment]
Hello, 

If you want to have more then one you can do regular structure
```
{
     "namespaceA": {
          "trans1": "Some Text 1",
          "trans2": "Some Text 2"
     },
     "namespaceB": {
          "trans1": "Some Text 3",
          "trans2": "Some Text 4"
     }
}
```

Property _namespace is dedicated to creating for namespace for current scope
