### ISSUE TITLE
hello tagType='h1' no workink

### ISSUE THREAD

**Issue by soyJSus** [vazco/meteor-universe-i18n#47]
Hello,   the file translation work but spam is not changed by h1

this is my componet

import React from 'react';
const T = i18n.createComponent(i18n.createTranslator('home'));

class AppContainer extends React.Component {
    constructor(props) {
        super(props);
        this.displayName = 'AppContainer';
    }
    render() {
        return <div>
        
       <T tagType='h1'>default_title</T>
       <T props={{ className: 'text-center'}}>default_description</T>
        
        </div>;
    }
}

export default AppContainer;

**Comment by cristo-rabani** [comment]
Hello,

Please try in this way:
```
<T _tagType='h1'>default_title</T>
```
