### ISSUE TITLE
How to load translation file?

### ISSUE THREAD

**Issue by joetidee** [vazco/meteor-universe-i18n#49]
In the API section of the docs it mentions `i18n.loadLocale(locale, params)` so is this what is used to load in a file of translations?
If so, do you also have to add the line `i18n.setLocale()` above it?
Also, where do you run these line - in the top of the file before the component, or in `componentDidMount` ?

Here is what I am trying so far and I am getting this error in the browser console:

> http://localhost:3000/universe/locale/en?ts=1477060272095 net::ERR_CONNECTION_REFUSED 

Code so far:

```
import { Meteor } from 'meteor/meteor';
import React from 'react';
import i18n from 'meteor/universe:i18n';

export default class MyComponent extends React.Component {
    componentDidMount() {
        i18n.setLocale("en-GB");
    }

    render(){
        return (
            <div>{i18n.__('hello_world')}</div>
        )
    }
};
```

The translation file for `/i18n/en-GB.i18n.json` is:

```
{
  "hello_world" : "Hello World!"
}
```

**Comment by cristo-rabani** [comment]
Hello Joetidee,

Translation files are loaded automatically according of meteor structure policy but should be placed on both sides.
Recommended file type for translation is YAML format.
