### ISSUE TITLE
ReferenceError: Can't find variable: i18n

### ISSUE THREAD

**Issue by celloudiallo** [vazco/meteor-universe-i18n#5]
Can't find the i18n variable on the client. I just added the package to my project for testing as follow:

1 - meteor add universe:i18n
2 - open browser console and type i18n
3 - ReferenceError: Can't find variable: i18n

Missing exports??

**Comment by cristo-rabani** [comment]
Hello Celloudiallo,

This is because this package doesn't provide global. 
Please import it using universe:modules in .import.jsx you can do that by:
```
import i18n from '{universe:i18n}';
```
In regular .js files you can import i18n using System.import
```
System.import('{universe:i18n}').then(function(m){ 
var i18n = m['default'];
//Your code;
 });
```

**Comment by celloudiallo** [comment]
Thanks for the response.

Any particular reason why there is no global variable provided?

**Comment by cristo-rabani** [comment]
This package is mostly for ECMAScript 2015 - modules
Mostly uses for react components.
This is useful for increase the performance of application.
Application will load only what need in current moment not everything at once.
This is important especially for biggest applications, mostly on client side.
Additionally modules are helpful in organization and understanding of application dependencies
e.g. You looking at file and you know, which things are used(or can be used here) and from where are taken.
In next version will be available global variable under `_i18n` ( many other packages using i18n and I want not collisions ). So you will might be used it, if someone doesn't want use of modules.

**Comment by nicolamr** [comment]
import doesn't work in .coffee and .cjsx files either.

**Comment by cristo-rabani** [comment]
Hello, 
New version is now available ( with global _i18n )

@nicolamr But we can use import without es6
```
System.import '{universe:i18n}' .then module ->
  i18n = module.i18n
```
