### ISSUE TITLE
on production, texts do only update if cache is cleared

### ISSUE THREAD

**Issue by macrozone** [vazco/meteor-universe-i18n#51]
We deployed a new version with changes in the yaml files.

The changes are not visible unless you clear the cache. Happens on IE and Chrome (and probably other browsers as well)

universe:i18n@1.9.0

**Comment by mstanuch** [comment]
Hi @macrozone,
sorry for my late answer. 

It is caused by `Cache-Control` header, by default `max-age` is set to 2628000 (~1 month). You can change it using API:
```js
i18n.setOptions({
    // (on the server side only) gives you the possibility to add/change response headers
    translationsHeaders = {'Cache-Control':'max-age=2628000'}
});
```
