### ISSUE TITLE
How to translations placeholder in ReactJS

### ISSUE THREAD

**Issue by holmanlam** [vazco/meteor-universe-i18n#64]
How to translations placeholder in ReactJS.

For example,
`<FormControl type='text' placeholder={<T>search</T>} />`

Many many Thanks!!

**Comment by janowsiany** [comment]
Hey
**TL;DR;**
```js
<FormControl type='text' placeholder={i18n.__('search')} />
```

I assume that you are using `react-bootstrap` package. I must say that i am not really into this package and i found it to be poorly documented. 
So if `placeholder` prop is just passed down to native input element then the code mentioned above might not work as `placeholder` of native input accepts only strings and `<T />` component wraps translation in `<span />` element.

Try solution from above and let us know if it worked.

**Comment by holmanlam** [comment]
Hi, janowsiany.
Thanks for your help.
If i using `placeholder = {i18n .__ ('search')}` can be display the content. But if changed to other languages, it does not immediately refresh the language.

**Comment by yudansha** [comment]
Any update on this?
I need this too. Would be great if this is possible.

**Comment by janowsiany** [comment]
@yudansha and @holmanlam sorry for such a long response time.

Currently i don't see other way that creating [HOC](https://facebook.github.io/react/docs/higher-order-components.html), something like this:
`withTranslation.js`
```js
import React, { Component } from 'react';

import i18n from 'meteor/universe:i18n';

export default function withTranslation() {
    return MyComponent => class withTranslation extends Component {
        constructor(props) {
            super(props);
            this.state = {systemlocale: '_'};
            this._invalidate = (locale) => {
                this.setState({systemlocale: locale});
            }

            this.translator = i18n.createTranslator();
        };

        componentWillMount() {
            i18n.onChangeLocale(this._invalidate);
        }

        componentWillUnmount() {
            i18n.offChangeLocale(this._invalidate);
        }

        render() {
            const translatedProps = Object.keys(this.props).reduce((acc, val) => {
                if (typeof this.props[val] !== 'string') return acc;
                return Object.assign(acc, {[val]: this.translator(this.props[val])});
            }, {})

          return (
            <MyComponent
                {...this.props}
                {...translatedProps}
            />
          );
        }
    }
}
```

So you can use this like:
```js
import {FormControl} from 'react-bootstrap';

import withPlaceholder from './withPlaceholder.js';

const TranslatedFormControl = withPlaceholder()(FormControl);

<TranslatedFormControl type='text' placeholder='search' />
```
In above case if there is translation for search string then it will be translated.

**NOTE** that type property might be also translated, so a solution for this may be keeping translations in some namespace.

Perhaps @radekmie or @cristo-rabani may suggest some other solution.

**Comment by cristo-rabani** [comment]
Hello, 

Check new version 1.10.0

Now you can do like that:

```jsx

<T _translateProps={['placeholder']}>
      <FormControl type='text' placeholder='search' />
</T>
```

**Comment by enzolutions** [comment]
Hi @cristo-rabani 

I am glad that this problem is resolved I am having the same issue I was thinking was a problem of Ant Design.

I am little confused about how the key is selected in your example for a placeholder, could you provide a more elaborated example.

Kind regards

**Comment by enzolutions** [comment]
I figure out the, you need to provide the name of the property that you want to translate and inside the property just put the key .

```
<FormItem>
                    {getFieldDecorator('password', {
                        rules: [{ required: true, message: i18n.__('pages.signIn.passwordMessage') }],
                    })(
                        <Translate _translateProps={['placeholder']}>
                            <Input prefix={<Icon type="lock" style={{ fontSize: 13 }} />} type="password" placeholder='pages.signIn.password' />
                        </Translate>
                    )}
                </FormItem>
```
I only have one missing piece to be able to have a full i18n interface with Ant Design.

As was mentioned at the beginning of this issues the function ** i18n.__()** doesn't update on the proper time. I cannot use the react component as a parameter of a function because a string is expected as you can see in the following example.

```
<FormItem>
                    {getFieldDecorator('userName', {
                        rules: [{
                            required: true, message: <Translate>pages.signIn.usernameMessage</Translate>}],
                    })(
                        <Translate _translateProps={['placeholder']}>
                            <Input prefix={<Icon type="user" style={{ fontSize: 13 }} />} placeholder='pages.signIn.username' />
                        </Translate>
                    )}
                </FormItem>
```
An object is returned, but a string is expected, I am wondering if could be added a pareter to force the component to return a string instead of an object. 

May I create an issue for a feature request?
