### ISSUE TITLE
Get Raw HTML from i18n ?

### ISSUE THREAD

**Issue by fadomire** [vazco/meteor-universe-i18n#66]
Hello,

i was wondering if it is possible to get raw html and not just text from this library ?

thanks

**Comment by cristo-rabani** [comment]
Yes, it should work:

```yml
myhtml: |
  <div>
    <a href="#">whatever</a>
  </div>
```

**Comment by fadomire** [comment]
sorry i did not understood what the code you show is supposed to be ?

maybe i should precise my question, i have a json file that gave my translations, and i use i18.__() to get the text.

can i put html inside my json and tell i18n to render it as html and not text ?
