### ISSUE TITLE
Console error after updating to current version

### ISSUE THREAD

**Issue by nk31** [vazco/meteor-universe-i18n#68]
Today I updated universe from version 1.11.2 to the current version.
After that I got the following error message in the console:

Exception while invoking method 'universe.i18n.setServerLocaleForConnection' Error: Did not check() all arguments during call to 'universe.i18n.setServerLocaleForConnection'
I20170525-13:50:42.003(2)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check.js:485:13)
I20170525-13:50:42.004(2)?     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:133:16)
I20170525-13:50:42.004(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
I20170525-13:50:42.005(2)?     at packages/ddp-server/livedata_server.js:719:19
I20170525-13:50:42.005(2)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170525-13:50:42.006(2)?     at packages/ddp-server/livedata_server.js:717:40
I20170525-13:50:42.006(2)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170525-13:50:42.007(2)?     at packages/ddp-server/livedata_server.js:715:46
I20170525-13:50:42.007(2)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
I20170525-13:50:42.007(2)?     at packages/ddp-server/livedata_server.js:559:43

I figured out that 

`function getLang() {
  return (
      (navigator.languages && navigator.languages[0]) ||
      navigator.language ||
      navigator.browserLanguage ||
      navigator.userLanguage ||
      'de'
  );
}

i18n.setLocale(getLang());
`
causes the error although I did not change anything at this code.

After downgrading to previous version everything works without error.

Maybe you can check this issue. 

Thx

**Comment by cristo-rabani** [comment]
Hello, 
Compatibility with `audit-argument-checks` should be fixed in `1.12.1`.
