### ISSUE TITLE
Current js-yaml load schema doesn't support merge key

### ISSUE THREAD

**Issue by cantonese84** [vazco/meteor-universe-i18n#69]
It seems the specified schema (FAILSAFE_SCHEMA) for loading yml files doesn't support merge key (<<).  Supporting merge key would be quite helpful in organizing translation, and lessen the need to switch namespace in the codes.  Is it possible to switch the schema to DEFAULT_SAFE_SCHEMA?

**Comment by cristo-rabani** [comment]
Hello, 
I think that we can use "DEFAULT_SAFE_SCHEMA" instead of currently used schema.
