### ISSUE TITLE
Parsing of Ukrainian (.ua) files does not work correctly

### ISSUE THREAD

**Issue by derwaldgeist** [vazco/meteor-universe-i18n#71]
Similar to #65, the discovery of Ukrainian files does not work as expected. I have the following language files in my i18n directory:

```
de.i18n.json
en.i18n.json
ru.i18n.json
ua.i18n.json
```

The first three files load correctly. For the `ua.i18n.json`, an error is thrown:
```
While processing files with universe:i18n (for target os.osx.x86_64):
   packages/travel:i18n/i18n/ua.i18n.json: Cannot find localization for file: [object Object] in package: travel:i18n.
   Please change file name or set _locale key in file
```

If I manually add `_locale: 'ua'` to the file, it works.

**Comment by cristo-rabani** [comment]
Hello, 
Ukrainian code is `uk` not `ua`, the `ua` is a code of country - not language.
Please check [iso639-2](http://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=uk)

**Comment by derwaldgeist** [comment]
Ooops, thanks for the info. So I was doing this wrong in my app for quite a long time. :-)
