### ISSUE TITLE
HTML in translation not working since version 1.14.0

### ISSUE THREAD

**Issue by DavidSichau** [vazco/meteor-universe-i18n#73]
There seems to be a breaking change between version 1.13.0 and version 1.14.0.

Before it was possible to include html code in your translation since version 1.14.0 this is not possible anymore. Is there a way to restore the old behaviour? I tried out `_purify={false}` but this did not work.

**Comment by cristo-rabani** [comment]
Using `.setOptions` set `purify: str=>str`

**Comment by derwaldgeist** [comment]
Will this set the option globally? If so, is there a way to do this only locally, i.e. for one single string?
