### ISSUE TITLE
i18n.createTranslator not reactive

### ISSUE THREAD

**Issue by LucasBassetti** [vazco/meteor-universe-i18n#75]
Hi,

I'm try to use the `i18n.createTranslator` but the translations just change if I refresh the page.

If I use the `i18n.createComponent` works fine but in some situations I need use the `i18n.createTranslator`.

Is there a option to make it reactive like `i18n.createComponent`?

Thank you!

**Comment by LucasBassetti** [comment]
I find the `i18n.createReactiveTranslator` but the same problem happens

**Comment by cristo-rabani** [comment]
Hello, 

Component `T` can wrap other component. 
Or add following piece of souce to your component:

```
componentDidMount () {
                this._invalidate = () => this.forceUpdate();
                i18n.on('changeLocale', this._invalidate);
            }

            componentWillUnmount () {
                i18n.off('changeLocale', this._invalidate);
            }
```

**Comment by tidx1995** [comment]
+1
