### ISSUE TITLE
Translations not updating on hot reload

### ISSUE THREAD

**Issue by derwaldgeist** [vazco/meteor-universe-i18n#78]
Quite often, if I change a translation file, this will cause the server to re-compile, but I cannot see the changes after hot-code-push. Only if I do `meteor reset` and restart the server, things show up correctly. What may cause this?

**Comment by cristo-rabani** [comment]
Hello, 

As a default in options is set `translationsHeaders = {'Cache-Control':'max-age=2628000'},`
Or you can load translations with flag `fresh: true`
