### ISSUE TITLE
Number as key name give wrong output

### ISSUE THREAD

**Issue by fadomire** [vazco/meteor-universe-i18n#79]
with a json file formatted like : 
`
{
  "hello": {
    "world": "stringvalue",
    "400": "anothervalue"
  }
}
`

When it goes trough utilities.js `set` function the line 22 `+keys[0] === +keys[0]` return true

The final output is an array with null value in it

It seems it is not allowed to have numbers as key name in our translations files but it is not clear in the doc that in your file to use arrays you can either write it as `[]` or an object with number as keynames `{"0": "hello", "1": "world"}`

**Comment by cristo-rabani** [comment]
Hello, 
Should be fixed in 1.20
