### ISSUE TITLE
Meteor 1.3 beta 4 - no translations

### ISSUE THREAD

**Issue by timothyarmes** [vazco/meteor-universe-i18n#8]
Hi,

I'm in the process of upgrading my project to use Meteor 1.3 with the new modules support.

Everything works with the exception of this project, which can't find my translations. If as if the son files have been ignored.

Thanks.

**Comment by cristo-rabani** [comment]
Hello, 

we will check soon compatibility with meteor 1.3 RC

Temporally solution, please try use with environment variable UNIVERSE_I18N_LOCALES = all ( it must be set before build is made )

**Comment by timothyarmes** [comment]
Hi. No, that doesn't solve it unfortunately.

**Comment by cristo-rabani** [comment]
Hello,
Please try to use new version 1.3.2.
If you will have still problem, let us know exactly what is it this bug. 
This package is working on clean project with METEOR@1.3-modules-beta.4

**Comment by timothyarmes** [comment]
Still not working. I'm trying to track it down now on a local fork. I can see that the build step gets called and the .js file is generated with the translation data. However that generated js file isn't found in either the server or client builds.

**Comment by timothyarmes** [comment]
I should add that I'm trying to translate a package, I haven't tested translation of local files.

**Comment by timothyarmes** [comment]
Hi,

Attached is a test that shows the problem.

[i18nTest.zip](https://github.com/vazco/meteor-universe-i18n/files/94933/i18nTest.zip)

I've tracked it down to ecmascript. If it's included (as specified in the app:test package)  then the translation fails. If it's removed then the translation works.

I don't know if this is a bug in ecmascript or in universe:i18n

**Comment by timothyarmes** [comment]
This is definitely a Meteor 1.3 bug. I've created a tiny test case and submitted it to them: https://github.com/meteor/meteor/issues/6031

**Comment by cristo-rabani** [comment]
Hello,

This bug is in package ecmascript because all files *.i18n.yml works with ecmascript.
This seems like ecmascript steals all jsons files.
Also, if you use universe:ecmascript instead of ecmascript all works too.

TIP: in blaze please also use package "universe:i18n-blaze".
