### ISSUE TITLE
Adding translations to the universe:i18n package at runtime

### ISSUE THREAD

**Issue by Subjekt2Change** [vazco/meteor-universe-i18n#82]
Please bear with me if this question sounds stupid, i have just begun working with react and am thus a greenhorn.

I am currently working on a system which should allow translators to create new translation files with already existing ones as templates. Additionally translators should be able to change existing translations in the back-end.

As far as i have understood all translation files are packed into the universe:i18n package. So i reckon adding / changing files in the /i18n/ folder via the node fileSystem (as i'm doing it now) would not have any effect once the project is complete.

My question is as follows: 
Is it possible to add / change translations inside the package at runtime?
If it is not possible can i cheat this by saving the files on another host?

I have already tried changing translations using the i18n.addTranslation command but sadly these are resetted  after a reload.

**Comment by cristo-rabani** [comment]
Hello @Subjekt2Change 

There are a few possibilities depending on what you want to do.
1. Any client can get translations form remotely server which potentially can be not own.
in option you can find  `hostUrl: 'http://current.host.url/',`
example:  `http://localhost:3000/universe/locale/en` which en is you locale

2. Server side can look like:

**Comment by jasongrishkoff** [comment]
Worth noting that under `refreshTranslations` there's a line that says `locale = i18n._normalize(locale);` -- I believe the underscore should be removed so it's just `locale = i18n.normalize(locale);`
