### ISSUE TITLE
Fallback Language

### ISSUE THREAD

**Issue by Koerner** [vazco/meteor-universe-i18n#84]
Is there an possibility to define a fall back language if the string is not available in the current local.

So lets say there is a translation `"fruit": "Apple"` in en but there is no in de. Then it would still show "Apple" because en is defined as fallback language.

**Comment by cristo-rabani** [comment]
Hello,

This issue soon will be checked and fixed if still exist

**Comment by cristo-rabani** [comment]
Hello,

Yes, You can set it in options e.g.:

```
i18n.setOptions({
    defaultLocale: 'de-DE'
});
```
