### ISSUE TITLE
Reactive helper for non React apps

### ISSUE THREAD

**Issue by HazemKhaled** [vazco/meteor-universe-i18n#87]
Hi,

I created this simple helper to use universe:i18n into regular Meteor app with Blaze template

```
Template.registerHelper('_', i18n.__);
```

Working fine, but not reactive, so we need to refresh after setLocale(), any hint to convert it to a reactive helper?

**Comment by cristo-rabani** [comment]
Hello, 

Please use `i18n.createReactiveTranslator`
