### ISSUE TITLE
Translation file in atmosphere package not loaded

### ISSUE THREAD

**Issue by u8621011** [vazco/meteor-universe-i18n#88]
I have a translation file in our local atmosphere package named "both\i18n\zh-TW.i18n.json" and content as below

```
{
    "_locale": "zh-TW",
    "Label Name": "標籤名稱"
}
```

in Meteor.startup of our app we set the locale like this
```
i18n.setLocale("zh-TW");
```

and in our translating atmosphere  package, we implemented a blaze helper to collect the translation but cannot get the tranlation.

```
import { i18n } from 'meteor/universe:i18n';
Template.listResult.helpers({
    headerTooltips() {
        let headerTooltips = {
            "Label Name" : i18n.__("Label Name")
            /*
            here we also tried 
            "Label Name" : i18n.__("our_package_name.Label Name")
            */
        };
        return headerTooltips;
    }
```

I traced into universe i18n and saw i18n._translations didn't load the package translation file.
I cannot figure out why and how to do, please help...

**Comment by cristo-rabani** [comment]
Hello, 
Did you have added as `api.use` in `package.js`?

**Comment by u8621011** [comment]
Hello Cristo,

I have added universe:i18n with app.use in package.js like this in my atmosphere package:
api.use('universe:i18n')

or do i need add codes in package.js for my zh-TW.i18n.json file?
(my zh-TW.i18n.json and the client component codes are all in the same atmosphere package)

**Comment by khaledbk** [comment]
@u8621011 
Package.onUse(function(api){
...
api.addFiles('*/*/en.i18n.json','client');
api.addFiles('*/*/i18n/en.i18n.json','server');
});
for me i added the files using api.addFiles it works !

**Comment by mathewmeconry** [comment]
try to start your project like this: ```sh UNIVERSE_I18N_LOCALES=all meteor  run```

as mentioned here the package only loads en on default: [incremental-loading-of-translations](https://github.com/vazco/meteor-universe-i18n#incremental-loading-of-translations)
