### ISSUE TITLE
Bug getting dialect locale from path

### ISSUE THREAD

**Issue by dovydaskukalis** [vazco/meteor-universe-i18n#92]
Locales like `pt-BR` don't work because it assigns it to `br` instead of `pt` group. 

`/universe/locale/pt` returns blank
`/universe/locale/pt-BR` returns blank
`/universe/locale/br` returns the locale however it doesn't work because the package is making calls to the first 2. 

I think the issue is `testIt` function in `builder.js`.  Because `br` is higher on the list of locales, regex matches it first.

My sample folder structure:
`i18n/pt-BR/test.i18n.yml`

**Comment by cristo-rabani** [comment]
Hello, 
Please check the current version (1.20). It should be fine
