### ISSUE TITLE
Empty translations with Meteor 1.7.0.1

### ISSUE THREAD

**Issue by royklopper** [vazco/meteor-universe-i18n#93]
Hi there,

I'm experiencing some issues with Meteor 1.7 and this package. Translations are not loaded and passed on to the frontend.

I've tested the same files on Meteor 1.6.x and that works properly. Calling "/universe/locale/en-US" on 1.7 returns an empty response, 1.6.x returns the proper Javascript signature.

Files added:
/i18n/en-US/test.i18n.yml

```
_locale: en-US
_namespace: test

key: test
```

calling `i18n.__('test.test')` returns a proper response in 1.6, but 1.7 it does not translate. 

If you need more info let me know.

Cheers

**Comment by cristo-rabani** [comment]
Hello,

We are currently working on it, so the update should be available soon.

Thanks.

**Comment by ivan133** [comment]
Any news?

**Comment by Adriano72** [comment]
It's 2 September. Any news???

**Comment by majeocpi** [comment]
Any news?

**Comment by majeocpi** [comment]
https://github.com/vazco/meteor-universe-i18n/issues/88#issuecomment-388341901

**Comment by cristo-rabani** [comment]
Hello, 
Should be fine in version 1.20.0

**Comment by ivan133** [comment]
I've tried with 1.20.1 just now and it doesn't work
I've tried to set UNIVERSE_I18N_LOCALES=all - didn't help

**Comment by Ethaan** [comment]
This is not working also for me, so i have something like this.

```
  "galaxy.meteor.com": {
    "env": {
      "DEPLOY_HOSTNAME":"galaxy.meteor.com",  
      "ROOT_URL": "",
      "MONGO_URL": "",
      "UNIVERSE_I18N_LOCALES": "es-ES,es"
    }
  },
```

And as you guys can see, on https://www.meetacreator.com/, no `spanish` is loaded, but if you click on the `usa` flag, it will show the english translations.

my translation lives on `lib/i18n/es.i18n.json` and `lib/i18n/en.i18n.json`

this is the name of the file `_locale`

```
  "_locale": "es-ES",
  "_namespace": "common",
  ...
```

**this works on development with no issues, but on production it dosen't**

**Comment by ivan133** [comment]
I didn't work with galaxy, but for mup Let me tell you the secret you need to setup UNIVERSE_I18N_LOCALES before building the app 
For example:
UNIVERSE_I18N_LOCALES=all mup deploy

**Comment by piotrpospiech** [comment]
Issue can't be reproduced in the newest version (`v1.32.4`)
