### ISSUE TITLE
Translations remain cached in CDN

### ISSUE THREAD

**Issue by KoenLav** [vazco/meteor-universe-i18n#94]
We make use of Cloudflare and whenever we create a new release the translations 'lag' one step behind, presumably because Cloudflare server them from cache (which is not invalidated).

**Comment by cristo-rabani** [comment]
Yes, Cloudflare made cached it. 
Please set header by options:
```
i18n.setOptions({
    translationsHeaders: {'Cache-Control':'no-cache'},
});
```

or load translation with fresh: true 
```
i18n.loadLocale(locale, {fresh: true});
```
