### ISSUE TITLE
How to render a react component as parameter?

### ISSUE THREAD

**Issue by arichter83** [vazco/meteor-universe-i18n#96]
I want to pass a component object as parameter, is there a way to do this?

The following code just displays "test [object Object]".

```
import { i18n } from 'meteor/universe:i18n';

render() {
  i18n.addTranslation('en', 'test_with_parameter', 'test {$para}');
  T = i18n.createComponent();
  var test = <h1>test</h1>;
  return (
    <div>
      {i18n.getTranslation('test_with_parameter', {para: test})}
      <T para={test}>test_with_parameter</T>
    </div>
}
```

**Comment by cristo-rabani** [comment]
Hello, 
Please check it out:

```
<T _translateProps={['title', 'children']}>
      <h1 title="Common.ok">Common.ok</h1>
</T>
```

**Comment by arichter83** [comment]
@cristo-rabani this was not the question, I want to use an object as parameter for the translation. It's not about the `<h1>test</h1>`, it's about the object test that should be rendered in the translation `test {$para}`.

I now think I could just `toString()` the test before, something like `<T para={test.toString()}>test_with_parameter</T>` but in the special case the JSX would than be quoted. I improvised by splitting the translation in two: `<T>test_pre</T>{test}<T>test_post</T>`
