### ISSUE TITLE
Typo at @types npm package name

### ISSUE THREAD

**Issue by arichter83** [vazco/meteor-universe-i18n#97]
The @types npm package has a spelling mistake:
https://www.npmjs.com/package/@types/meteor-univserse-i18n

univserse

**Comment by MacRusher** [comment]
Thanks @arichter83 for being vigilant!

DefinitelyTyped universe-i18n package is not maintained by us, but we created a [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27843) to fix this and it's already merged.
